### ISSUE TITLE
rust language server crash

### ISSUE THREAD

**Issue by JustFrederik** [zed-industries/zed#11136]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

This appeared while using zed for no apparent reason. I don't think it's a problem with the language server since it isn't crashing in rustrover. 

### Environment

Zed: v0.133.3 (Zed Preview)
OS: macOS 14.0.0
Memory: 16 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

```
2024-04-28T19:03:22+02:00 [INFO] ========== starting zed ==========
2024-04-28T19:03:22+02:00 [INFO] Opening main db
2024-04-28T19:03:22+02:00 [INFO] Using git binary path: Some("/Applications/Zed Preview.app/Contents/MacOS/git")
2024-04-28T19:03:22+02:00 [ERROR] crates/theme/src/settings.rs:368: theme not found: Ultimate Dark Neo
2024-04-28T19:03:22+02:00 [INFO] extensions updated. loading 67, reloading 0, unloading 0
2024-04-28T19:03:22+02:00 [ERROR] crates/zed/src/zed.rs:660: EOF while parsing a value at line 1 column 0
2024-04-28T19:03:22+02:00 [INFO] Opening main db
2024-04-28T19:03:22+02:00 [INFO] building git repository, `.git` path in the worktree: "crates/crate1/.git"
2024-04-28T19:03:22+02:00 [ERROR] crates/git/src/repository.rs:122: Error { code: -9, klass: 4, message: "reference 'refs/heads/master' not found" }
2024-04-28T19:03:22+02:00 [INFO] set environment variables ...
```
crates/git/src/repository.rs:122 for each member of the workspace
```
2024-04-28T19:03:22+02:00 [INFO] building git repository, `.git` path in the worktree: "crates/plugin/.git"
2024-04-28T19:03:22+02:00 [ERROR] /Users/administrator/actions-runner-2/_work/zed/zed/crates/task/src/static_source.rs:38: Error("EOF while parsing a value", line: 23, column: 0)
2024-04-28T19:03:22+02:00 [INFO] Opening main db
2024-04-28T19:03:22+02:00 [INFO] set status on client 0: Authenticating
2024-04-28T19:03:22+02:00 [INFO] Opening main db
2024-04-28T19:03:22+02:00 [INFO] set status on client 119171: Connecting
2024-04-28T19:03:22+02:00 [ERROR] crates/workspace/src/persistence/model.rs:314: failed to read path after update
2024-04-28T19:03:22+02:00 [ERROR] crates/workspace/src/persistence/model.rs:314: No path stored for this editor
2024-04-28T19:03:23+02:00 [ERROR] crates/theme/src/settings.rs:368: theme not found: Ultimate Dark Neo
2024-04-28T19:03:23+02:00 [ERROR] failed to get git blame data: Failed to blame "src/lib.rs"

Caused by:
    0: failed to get commit messages
    1: 'git show' failed with error ExitStatus(unix_wait_status(32768))
2024-04-28T19:03:23+02:00 [ERROR] failed to get git blame data: Failed to blame "src/main.rs"

Caused by:
    0: failed to get commit messages
    1: 'git show' failed with error ExitStatus(unix_wait_status(32768))
2024-04-28T19:03:23+02:00 [ERROR] crates/theme/src/settings.rs:368: theme not found: Ultimate Dark Neo
2024-04-28T19:03:23+02:00 [INFO] starting language servers for Rust: rust-analyzer
2024-04-28T19:03:23+02:00 [INFO] starting language server "rust-analyzer", path: "/Users/admin/code/project", id: 1
2024-04-28T19:03:23+02:00 [INFO] starting language servers for Rust: rust-analyzer
2024-04-28T19:03:23+02:00 [INFO] starting language servers for Rust: rust-analyzer
2024-04-28T19:03:23+02:00 [INFO] starting language servers for Rust: rust-analyzer
2024-04-28T19:03:23+02:00 [INFO] fetching latest version of language server "rust-analyzer"
2024-04-28T19:03:23+02:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-04-28T19:03:24+02:00 [INFO] starting language servers for Rust: rust-analyzer
2024-04-28T19:03:24+02:00 [INFO] starting language servers for Rust: rust-analyzer
2024-04-28T19:03:24+02:00 [INFO] add connection to peer
2024-04-28T19:03:24+02:00 [INFO] add_connection;
2024-04-28T19:03:24+02:00 [INFO] waiting for server hello
2024-04-28T19:03:24+02:00 [INFO] got server hello
2024-04-28T19:03:24+02:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 396, id: 1071852 })
2024-04-28T19:03:24+02:00 [INFO] set status on client 119171: Connected { peer_id: PeerId { owner_id: 396, id: 1071852 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-04-28T19:03:24+02:00 [INFO] downloading language server "rust-analyzer"
2024-04-28T19:03:24+02:00 [INFO] starting language server. binary path: "/Users/admin/Library/Application Support/Zed/languages/rust-analyzer/rust-analyzer-2024-04-22", working directory:  "/Users/admin/code/project",, args: []
2024-04-28T19:03:34+02:00 [ERROR] failed to get git blame data: Failed to blame "src/main.rs"

Caused by:
    0: failed to get commit messages
    1: 'git show' failed with error ExitStatus(unix_wait_status(32768))
2024-04-28T19:03:36+02:00 [ERROR] failed to get git blame data: Failed to blame "src/main.rs"

Caused by:
    0: failed to get commit messages
    1: 'git show' failed with error ExitStatus(unix_wait_status(32768))
2024-04-28T19:03:41+02:00 [INFO] starting language servers for Rust: rust-analyzer
2024-04-28T19:03:41+02:00 [INFO] starting language servers for Rust: rust-analyzer
2024-04-28T19:03:41+02:00 [INFO] starting language servers for Rust: rust-analyzer
2024-04-28T19:03:41+02:00 [INFO] starting language servers for Rust: rust-analyzer
2024-04-28T19:03:43+02:00 [ERROR] crates/lsp/src/lsp.rs:352: cannot read LSP message headers
2024-04-28T19:03:43+02:00 [WARN] Generic lsp request to rust-analyzer failed: oneshot canceled
2024-04-28T19:03:43+02:00 [WARN] Generic lsp request to rust-analyzer failed: oneshot canceled
2024-04-28T19:03:43+02:00 [WARN] Generic lsp request to rust-analyzer failed: oneshot canceled
2024-04-28T19:03:43+02:00 [WARN] Generic lsp request to rust-analyzer failed: oneshot canceled
2024-04-28T19:03:43+02:00 [ERROR] crates/editor/src/editor.rs:3876: oneshot canceled
2024-04-28T19:03:43+02:00 [ERROR] inlay hint update task for range Anchor { timestamp: Lamport {0: 1}, offset: 4647, bias: Left, buffer_id: Some(BufferId(4294967373)) }..Anchor { timestamp: Lamport {0: 1}, offset: 5225, bias: Right, buffer_id: Some(BufferId(4294967373)) } failed: inlay hint fetch task: inlay hints LSP request: oneshot canceled
2024-04-28T19:03:43+02:00 [ERROR] inlay hint update task for range Anchor { timestamp: Lamport {0: 1}, offset: 4647, bias: Left, buffer_id: Some(BufferId(4294967373)) }..Anchor { timestamp: Lamport {0: 1}, offset: 5225, bias: Right, buffer_id: Some(BufferId(4294967373)) } failed: inlay hint fetch task: inlay hints LSP request: oneshot canceled
2024-04-28T19:03:43+02:00 [WARN] Generic lsp request to rust-analyzer failed: server shut down
2024-04-28T19:03:43+02:00 [ERROR] crates/lsp/src/lsp.rs:374: Broken pipe (os error 32)
2024-04-28T19:03:43+02:00 [WARN] Generic lsp request to rust-analyzer failed: server shut down
2024-04-28T19:03:43+02:00 [ERROR] crates/project/src/project.rs:6949: server shut down
2024-04-28T19:03:43+02:00 [WARN] Generic lsp request to rust-analyzer failed: server shut down
2024-04-28T19:03:43+02:00 [ERROR] crates/project/src/project.rs:6949: server shut down
2024-04-28T19:03:43+02:00 [WARN] Generic lsp request to rust-analyzer failed: server shut down
2024-04-28T19:03:43+02:00 [ERROR] crates/editor/src/editor.rs:8417: failed to format via language server

Caused by:
    server shut down
2024-04-28T19:03:43+02:00 [ERROR] crates/project/src/project.rs:2710: sending into a closed channel
2024-04-28T19:03:43+02:00 [ERROR] failed to get git blame data: Failed to blame "src/main.rs"

Caused by:
    0: failed to get commit messages
    1: 'git show' failed with error ExitStatus(unix_wait_status(32768))
2024-04-28T19:03:43+02:00 [WARN] Generic lsp request to rust-analyzer failed: server shut down
2024-04-28T19:03:43+02:00 [WARN] Generic lsp request to rust-analyzer failed: server shut down
2024-04-28T19:03:44+02:00 [WARN] Generic lsp request to rust-analyzer failed: server shut down
2024-04-28T19:03:44+02:00 [WARN] Generic lsp request to rust-analyzer failed: server shut down
2024-04-28T19:03:44+02:00 [ERROR] inlay hint update task for range Anchor { timestamp: Lamport {0: 1}, offset: 5226, bias: Left, buffer_id: Some(BufferId(4294967373)) }..Anchor { timestamp: Lamport {65535: 4294967295}, offset: 18446744073709551615, bias: Right, buffer_id: None } failed: inlay hint fetch task: inlay hints LSP request: server shut down
2024-04-28T19:03:44+02:00 [ERROR] inlay hint update task for range Anchor { timestamp: Lamport {0: 1}, offset: 5451, bias: Left, buffer_id: Some(BufferId(4294967373)) }..Anchor { timestamp: Lamport {0: 1}, offset: 5692, bias: Right, buffer_id: Some(BufferId(4294967373)) } failed: inlay hint fetch task: inlay hints LSP request: server shut down
2024-04-28T19:03:44+02:00 [WARN] Generic lsp request to rust-analyzer failed: server shut down
2024-04-28T19:03:44+02:00 [ERROR] crates/project/src/project.rs:6949: server shut down
2024-04-28T19:03:44+02:00 [WARN] Generic lsp request to rust-analyzer failed: server shut down
2024-04-28T19:03:44+02:00 [ERROR] inlay hint update task for range Anchor { timestamp: Lamport {0: 1}, offset: 4647, bias: Left, buffer_id: Some(BufferId(4294967373)) }..Anchor { timestamp: Lamport {0: 1}, offset: 5225, bias: Right, buffer_id: Some(BufferId(4294967373)) } failed: inlay hint fetch task: inlay hints LSP request: server shut down
2024-04-28T19:03:45+02:00 [ERROR] failed to get git blame data: Failed to blame "src/main.rs"

Caused by:
    0: failed to get commit messages
    1: 'git show' failed with error ExitStatus(unix_wait_status(32768))
2024-04-28T19:03:45+02:00 [ERROR] failed to get git blame data: failed to get buffer project path
```

Lsp logs:
```
stderr: Panic context:
stderr: > fetch_native_diagnostics
stderr:
stderr: thread 'Worker' panicked at crates/hir-ty/src/builder.rs:82:9:
stderr: assertion failed: self.remaining() > 0
stderr: stack backtrace:
stderr: 0: _rust_begin_unwind
stderr: 1: core::panicking::panic_fmt
stderr: 2: core::panicking::panic
stderr: 3: hir_ty::builder::TyBuilder<D>::push
stderr: 4: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 5: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
stderr: 6: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 7: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
stderr: 8: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 9: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
stderr: 10: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
stderr: 11: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 12: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_return
stderr: 13: hir_ty::infer::infer_query
stderr: 14: salsa::Cycle::catch
stderr: 15: salsa::derived::slot::Slot<Q,MP>::execute
stderr: 16: salsa::derived::slot::Slot<Q,MP>::read
stderr: 17: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
stderr: 18: <DB as hir_ty::db::HirDatabase>::infer
stderr: 19: hir::DefWithBody::diagnostics
stderr: 20: hir::ModuleDef::diagnostics
stderr: 21: hir::Module::diagnostics
stderr: 22: ide_diagnostics::diagnostics
stderr: 23: salsa::Cancelled::catch
stderr: 24: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
stderr: 25: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
stderr: 26: rust_analyzer::diagnostics::fetch_native_diagnostics
stderr: 27: core::ops::function::FnOnce::call_once{{vtable.shim}}
stderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stderr: Panic context:
stderr: > fetch_native_diagnostics
stderr:
stderr: thread 'Worker' panicked at crates/hir-ty/src/builder.rs:82:9:
stderr: assertion failed: self.remaining() > 0
stderr: stack backtrace:
stderr: 0: _rust_begin_unwind
stderr: 1: core::panicking::panic_fmt
stderr: 2: core::panicking::panic
stderr: 3: hir_ty::builder::TyBuilder<D>::push
stderr: 4: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 5: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
stderr: 6: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 7: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
stderr: 8: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 9: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
stderr: 10: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
stderr: 11: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 12: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_return
stderr: 13: hir_ty::infer::infer_query
stderr: 14: salsa::Cycle::catch
stderr: 15: salsa::derived::slot::Slot<Q,MP>::execute
stderr: 16: salsa::derived::slot::Slot<Q,MP>::read
stderr: 17: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
stderr: 18: <DB as hir_ty::db::HirDatabase>::infer
stderr: 19: hir::DefWithBody::diagnostics
stderr: 20: hir::ModuleDef::diagnostics
stderr: 21: hir::Module::diagnostics
stderr: 22: ide_diagnostics::diagnostics
stderr: 23: salsa::Cancelled::catch
stderr: 24: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
stderr: 25: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
stderr: 26: rust_analyzer::diagnostics::fetch_native_diagnostics
stderr: 27: core::ops::function::FnOnce::call_once{{vtable.shim}}
stderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stderr: Panic context:
stderr: > fetch_native_diagnostics
stderr:
stderr: thread 'Worker' panicked at crates/hir-ty/src/builder.rs:82:9:
stderr: assertion failed: self.remaining() > 0
stderr: stack backtrace:
stderr: 0: _rust_begin_unwind
stderr: 1: core::panicking::panic_fmt
stderr: 2: core::panicking::panic
stderr: 3: hir_ty::builder::TyBuilder<D>::push
stderr: 4: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 5: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
stderr: 6: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 7: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
stderr: 8: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 9: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
stderr: 10: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
stderr: 11: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 12: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_return
stderr: 13: hir_ty::infer::infer_query
stderr: 14: salsa::Cycle::catch
stderr: 15: salsa::derived::slot::Slot<Q,MP>::execute
stderr: 16: salsa::derived::slot::Slot<Q,MP>::read
stderr: 17: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
stderr: 18: <DB as hir_ty::db::HirDatabase>::infer
stderr: 19: hir::DefWithBody::diagnostics
stderr: 20: hir::ModuleDef::diagnostics
stderr: 21: hir::Module::diagnostics
stderr: 22: ide_diagnostics::diagnostics
stderr: 23: salsa::Cancelled::catch
stderr: 24: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
stderr: 25: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
stderr: 26: rust_analyzer::diagnostics::fetch_native_diagnostics
stderr: 27: core::ops::function::FnOnce::call_once{{vtable.shim}}
stderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stderr: Panic context:
stderr: > fetch_native_diagnostics
stderr:
stderr: thread 'Worker' panicked at crates/hir-ty/src/builder.rs:82:9:
stderr: assertion failed: self.remaining() > 0
stderr: stack backtrace:
stderr: 0: _rust_begin_unwind
stderr: 1: core::panicking::panic_fmt
stderr: 2: core::panicking::panic
stderr: 3: hir_ty::builder::TyBuilder<D>::push
stderr: 4: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 5: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
stderr: 6: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 7: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
stderr: 8: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 9: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
stderr: 10: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
stderr: 11: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 12: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_return
stderr: 13: hir_ty::infer::infer_query
stderr: 14: salsa::Cycle::catch
stderr: 15: salsa::derived::slot::Slot<Q,MP>::execute
stderr: 16: salsa::derived::slot::Slot<Q,MP>::read
stderr: 17: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
stderr: 18: <DB as hir_ty::db::HirDatabase>::infer
stderr: 19: hir::DefWithBody::diagnostics
stderr: 20: hir::ModuleDef::diagnostics
stderr: 21: hir::Module::diagnostics
stderr: 22: ide_diagnostics::diagnostics
stderr: 23: salsa::Cancelled::catch
stderr: 24: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
stderr: 25: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
stderr: 26: rust_analyzer::diagnostics::fetch_native_diagnostics
stderr: 27: core::ops::function::FnOnce::call_once{{vtable.shim}}
stderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stderr: Panic context:
stderr: > fetch_native_diagnostics
stderr:
stderr: thread 'Worker' panicked at crates/hir-ty/src/builder.rs:82:9:
stderr: assertion failed: self.remaining() > 0
stderr: stack backtrace:
stderr: 0: _rust_begin_unwind
stderr: 1: core::panicking::panic_fmt
stderr: 2: core::panicking::panic
stderr: 3: hir_ty::builder::TyBuilder<D>::push
stderr: 4: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 5: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
stderr: 6: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 7: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
stderr: 8: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 9: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
stderr: 10: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
stderr: 11: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 12: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_return
stderr: 13: hir_ty::infer::infer_query
stderr: 14: salsa::Cycle::catch
stderr: 15: salsa::derived::slot::Slot<Q,MP>::execute
stderr: 16: salsa::derived::slot::Slot<Q,MP>::read
stderr: 17: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
stderr: 18: <DB as hir_ty::db::HirDatabase>::infer
stderr: 19: hir::DefWithBody::diagnostics
stderr: 20: hir::ModuleDef::diagnostics
stderr: 21: hir::Module::diagnostics
stderr: 22: ide_diagnostics::diagnostics
stderr: 23: salsa::Cancelled::catch
stderr: 24: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
stderr: 25: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
stderr: 26: rust_analyzer::diagnostics::fetch_native_diagnostics
stderr: 27: core::ops::function::FnOnce::call_once{{vtable.shim}}
stderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stderr: Panic context:
stderr: > fetch_native_diagnostics
stderr:
stderr: thread 'Worker' panicked at crates/hir-ty/src/builder.rs:82:9:
stderr: assertion failed: self.remaining() > 0
stderr: stack backtrace:
stderr: 0: _rust_begin_unwind
stderr: 1: core::panicking::panic_fmt
stderr: 2: core::panicking::panic
stderr: 3: hir_ty::builder::TyBuilder<D>::push
stderr: 4: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 5: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
stderr: 6: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 7: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
stderr: 8: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 9: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
stderr: 10: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
stderr: 11: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 12: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_return
stderr: 13: hir_ty::infer::infer_query
stderr: 14: salsa::Cycle::catch
stderr: 15: salsa::derived::slot::Slot<Q,MP>::execute
stderr: 16: salsa::derived::slot::Slot<Q,MP>::read
stderr: 17: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
stderr: 18: <DB as hir_ty::db::HirDatabase>::infer
stderr: 19: hir::DefWithBody::diagnostics
stderr: 20: hir::ModuleDef::diagnostics
stderr: 21: hir::Module::diagnostics
stderr: 22: ide_diagnostics::diagnostics
stderr: 23: salsa::Cancelled::catch
stderr: 24: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
stderr: 25: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
stderr: 26: rust_analyzer::diagnostics::fetch_native_diagnostics
stderr: 27: core::ops::function::FnOnce::call_once{{vtable.shim}}
stderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stderr: Panic context:
stderr: > fetch_native_diagnostics
stderr:
stderr: thread 'Worker' panicked at crates/hir-ty/src/builder.rs:82:9:
stderr: assertion failed: self.remaining() > 0
stderr: stack backtrace:
stderr: 0: _rust_begin_unwind
stderr: 1: core::panicking::panic_fmt
stderr: 2: core::panicking::panic
stderr: 3: hir_ty::builder::TyBuilder<D>::push
stderr: 4: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 5: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::check_call_arguments
stderr: 6: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 7: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
stderr: 8: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 9: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
stderr: 10: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
stderr: 11: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
stderr: 12: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_return
stderr: 13: hir_ty::infer::infer_query
stderr: 14: salsa::Cycle::catch
stderr: 15: salsa::derived::slot::Slot<Q,MP>::execute
stderr: 16: salsa::derived::slot::Slot<Q,MP>::read
stderr: 17: <salsa::derived::DerivedStorage<Q,MP> as salsa::plumbing::QueryStorageOps<Q>>::fetch
stderr: 18: <DB as hir_ty::db::HirDatabase>::infer
stderr: 19: hir::DefWithBody::diagnostics
stderr: 20: hir::ModuleDef::diagnostics
stderr: 21: hir::Module::diagnostics
stderr: 22: ide_diagnostics::diagnostics
stderr: 23: salsa::Cancelled::catch
stderr: 24: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
stderr: 25: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
stderr: 26: rust_analyzer::diagnostics::fetch_native_diagnostics
stderr: 27: core::ops::function::FnOnce::call_once{{vtable.shim}}
stderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stderr: thread 'LspServer' panicked at /Users/runner/work/rust-analyzer/rust-analyzer/crates/stdx/src/thread/pool.rs:86:35:
stderr: called `Result::unwrap()` on an `Err` value: "SendError(..)"
stderr: stack backtrace:
stderr: 0: _rust_begin_unwind
stderr: 1: core::panicking::panic_fmt
stderr: 2: core::result::unwrap_failed
stderr: 3: rust_analyzer::task_pool::TaskPool<T>::spawn
stderr: 4: rust_analyzer::dispatch::RequestDispatcher::on_with_thread_intent
stderr: 5: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::on_request
stderr: 6: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::handle_event
stderr: 7: rust_analyzer::main_loop::<impl rust_analyzer::global_state::GlobalState>::run
stderr: 8: rust_analyzer::main_loop::main_loop
stderr: 9: rust_analyzer::run_server
stderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stderr: thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lsp-server-0.7.6/src/stdio.rs:28:37:
stderr: receiver was dropped, failed to send a message: "SendError(..)"
stderr: stack backtrace:
stderr: 0: _rust_begin_unwind
stderr: 1: core::panicking::panic_fmt
stderr: 2: core::result::unwrap_failed
stderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stderr: thread 'main' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jod-thread-0.1.2/src/lib.rs:33:22:
stderr: called `Result::unwrap()` on an `Err` value: Any { .. }
stderr: stack backtrace:
stderr: 0: _rust_begin_unwind
stderr: 1: core::panicking::panic_fmt
stderr: 2: core::result::unwrap_failed
stderr: 3: jod_thread::JoinHandle<T>::join
stderr: 4: stdx::thread::JoinHandle<T>::join
stderr: 5: rust_analyzer::main
stderr: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by SomeoneToIgnore** [comment]
> isn't crashing in rustrover

RustRover uses a totally different approach to Rust analysis, not related to rust-analyzer, so not surprising that it does not crash.

Albeit I cannot be 100% sure that it's not Zed problem, but 90% sure that isn't.
Can you double check in VSCode/NeoVim/Helix/Fleet/anything else with r-a ?

**Comment by JustFrederik** [comment]
Seems like it's a problem with the vscode binary. It crashed in vscode too, so I installed rust-analyzer with rustup and that worked(uninstalling the extension&removing .cargo did not work).
