### ISSUE TITLE
macOS: GPUI crashes when pressing any key

### ISSUE THREAD

**Issue by bho01** [zed-industries/zed#11239]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

On the latest changeset of GPUI, I ran the Hello World example (with minor modifications). However, when you press any key while the program is running, it crashes.

On the debug binary:
`
thread 'main' panicked at /Users/brendonho/.cargo/git/checkouts/zed-23861290b5d2093f/06674a2/crates/gpui/src/key_dispatch.rs:444:9:
assertion failed: !self.nodes.is_empty()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

On the release binary:
`
thread 'main' panicked at /Users/brendonho/.cargo/git/checkouts/zed-23861290b5d2093f/06674a2/crates/gpui/src/key_dispatch.rs:396:41:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

### Environment

Zed: v0.132.5 (Zed)
OS: macOS 14.3.1
Memory: 64 GiB
Architecture: aarch64

**Comment by bho01** [comment]
I was on an old version of GPUI. This issue is not seen anymore. Will close
