### ISSUE TITLE
error: failed to run custom build command for `rpc v0.1.0 (D:\GitHub Repository\zed\crates\rpc)`

### ISSUE THREAD

**Issue by Break-Unrestrained** [zed-industries/zed#11640]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I run 
1. `git submodule update --init --recursive`
2. `rustup update`
3. `rustup target add wasm32-wasi`
4. finally, when i run `cargo run -- release`, it say:

error: failed to run custom build command for `rpc v0.1.0 (D:\GitHub Repository\zed\crates\rpc)`

Caused by:
  process didn't exit successfully: `D:\GitHub Repository\zed\target\release\build\rpc-639244f615967765\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at crates\rpc\build.rs:6:10:
  called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "protoc failed: C:\\Users\\���˸�\\AppData\\Local\\Temp\\prost-buildrDlTRw\\prost-descriptor-set: No such file or directory\r\n" }
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:645
     1: core::panicking::panic_fmt
               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:72
     2: core::result::unwrap_failed
               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\result.rs:1654
     3: enum2$<core::result::Result<tuple$<>,std::io::error::Error> >::unwrap
               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\core\src\result.rs:1077
     4: build_script_build::main
               at .\build.rs:3
     5: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\core\src\ops\function.rs:250
     6: core::hint::black_box
               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\core\src\hint.rs:337
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
how to solve it ?

### Environment

Window11
12th Gen Intel(R) Core(TM) i5-12500H

**Comment by slava110** [comment]
Hi. I've tried to use Rust nightly - didn't help. This is probably caused by non-latin characters in the path.
![image](https://github.com/zed-industries/zed/assets/26705162/790f8504-b71d-4e70-8607-81f33f17a47f)
![image](https://github.com/zed-industries/zed/assets/26705162/11139bba-2c03-44e6-bded-71a7dd75c25d)
