### ISSUE TITLE
`fatal runtime error: IO Safety violation: owned file descriptor already closed` on linux

### ISSUE THREAD

**Issue by jakobhellermann** [zed-industries/zed#12114]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

When running zed (`cargo zed`) on linux, the process crashes trying to open the alacritty terminal with 
```
fatal runtime error: IO Safety violation: owned file descriptor already closed
```

https://github.com/zed-industries/zed/blob/7c9c80d66345940c80e59046d5273c3af59f38a9/crates/terminal/src/terminal.rs#L377
https://docs.rs/alacritty_terminal/0.23.0/src/alacritty_terminal/tty/unix.rs.html#285

<details>
<summary>Full backtrace:</summary>

```rs
#4  0x0000555560c22d4a in std::sys::pal::unix::abort_internal () at library/std/src/sys/pal/unix/mod.rs:366
#5  0x000055555fccc152 in std::sys::pal::unix::fs::debug_assert_fd_is_open ()
    at /rustc/791adf759cc065316f054961875052d5bc03e16c/library/std/src/rt.rs:43
#6  0x000055555fcd22bc in std::os::fd::owned::{impl#7}::drop () at /rustc/791adf759cc065316f054961875052d5bc03e16c/library/std/src/os/fd/owned.rs:181
#7  0x000055555fccf2f6 in core::ptr::drop_in_place<std::os::fd::owned::OwnedFd> ()
    at /rustc/791adf759cc065316f054961875052d5bc03e16c/library/core/src/ptr/mod.rs:542
#8  0x000055555cde1fd7 in core::ptr::drop_in_place<std::sys::pal::unix::fd::FileDesc> ()
    at /rustc/791adf759cc065316f054961875052d5bc03e16c/library/core/src/ptr/mod.rs:542
#9  0x000055555cde2659 in core::ptr::drop_in_place<std::sys::pal::unix::process::process_common::Stdio> ()
    at /rustc/791adf759cc065316f054961875052d5bc03e16c/library/core/src/ptr/mod.rs:542
#10 0x000055555cde1815 in core::ptr::drop_in_place<core::option::Option<std::sys::pal::unix::process::process_common::Stdio>> ()
    at /rustc/791adf759cc065316f054961875052d5bc03e16c/library/core/src/ptr/mod.rs:542
#11 0x000055555cde28cc in core::ptr::drop_in_place<std::sys::pal::unix::process::process_common::Command> ()
    at /rustc/791adf759cc065316f054961875052d5bc03e16c/library/core/src/ptr/mod.rs:542
#12 0x000055555cde1f07 in core::ptr::drop_in_place<std::process::Command> ()
    at /rustc/791adf759cc065316f054961875052d5bc03e16c/library/core/src/ptr/mod.rs:542
#13 0x000055555cdeba31 in alacritty_terminal::tty::unix::new () at src/tty/unix.rs:285
#14 0x000055555cd17913 in terminal::TerminalBuilder::new () at crates/terminal/src/terminal.rs:377
#15 0x000055555c93be62 in project::Project::create_terminal () at crates/project/src/terminals.rs:233
#16 0x000055555b13ec1f in terminal_view::{impl#7}::deserialize::{closure#0}::{async_block#0}::{closure#1} ()
    at crates/terminal_view/src/terminal_view.rs:904
#17 0x000055555b1d827a in gpui::window::{impl#22}::update_model<project::Project, core::result::Result<gpui::app::entity_map::Model<terminal::Terminal>, anyhow::Error>, terminal_view::{impl#7}::deserialize::{closure#0}::{async_block#0}::{closure_env#1}> () at crates/gpui/src/window.rs:3559
#18 0x000055555b186d13 in gpui::app::async_context::{impl#3}::update_model::{closure#0}<project::Project, core::result::Result<gpui::app::entity_map::Model<terminal::Terminal>, anyhow::Error>, terminal_view::{impl#7}::deserialize::{closure#0}::{async_block#0}::{closure_env#1}> ()
    at crates/gpui/src/app/async_context.rs:336
#19 0x000055555b1aba16 in gpui::app::{impl#5}::update_window::{closure#0}<core::result::Result<gpui::app::entity_map::Model<terminal::Terminal>, anyhow::Error>, gpui::app::async_context::{impl#3}::update_model::{closure_env#0}<project::Project, core::result::Result<gpui::app::entity_map::Model<terminal::Terminal>, anyhow::Error>, terminal_view::{impl#7}::deserialize::{closure#0}::{async_block#0}::{closure_env#1}>> ()
    at crates/gpui/src/app.rs:1339
#20 0x000055555b19fe46 in gpui::app::AppContext::update<core::result::Result<core::result::Result<gpui::app::entity_map::Model<terminal::Terminal>, anyhow::Error>, anyhow::Error>, gpui::app::{impl#5}::update_window::{closure_env#0}<core::result::Result<gpui::app::entity_map::Model<terminal::Terminal>, anyhow::Error>, gpui::app::async_context::{impl#3}::update_model::{closure_env#0}<project::Project, core::result::Result<gpui::app::entity_map::Model<terminal::Terminal>, anyhow::Error>, terminal_view::{impl#7}::deserialize::{closure#0}::{async_block#0}::{closure_env#1}>>> ()
    at crates/gpui/src/app.rs:361
#21 0x000055555b1a0e07 in gpui::app::{impl#5}::update_window<core::result::Result<gpui::app::entity_map::Model<terminal::Terminal>, anyhow::Error>, gpui::app::async_context::{impl#3}::update_model::{closure_env#0}<project::Project, core::result::Result<gpui::app::entity_map::Model<terminal::Terminal>, anyhow::Error>, terminal_view::{impl#7}::deserialize::{closure#0}::{async_block#0}::{closure_env#1}>> () at crates/gpui/src/app.rs:1330
#22 0x000055555b186bcc in gpui::app::async_context::{impl#0}::update_window<core::result::Result<gpui::app::entity_map::Model<terminal::Terminal>, anyhow::Error>, gpui::app::async_context::{impl#3}::update_model::{closure_env#0}<project::Project, core::result::Result<gpui::app::entity_map::Model<terminal::Terminal>, anyhow::Error>, terminal_view::{impl#7}::deserialize::{closure#0}::{async_block#0}::{closure_env#1}>> ()
    at crates/gpui/src/app/async_context.rs:91
#23 0x000055555b186f61 in gpui::app::async_context::{impl#3}::update_window<core::result::Result<gpui::app::entity_map::Model<terminal::Terminal>, anyhow::Error>, gpui::app::async_context::{impl#3}::update_model::{closure_env#0}<project::Project, core::result::Result<gpui::app::entity_map::Model<terminal::Terminal>, anyhow::Error>, terminal_view::{impl#7}::deserialize::{closure#0}::{async_block#0}::{closure_env#1}>> ()
    at crates/gpui/src/app/async_context.rs:354
#24 0x000055555b1cd2dc in gpui::window::AnyWindowHandle::update<gpui::app::async_context::AsyncWindowContext, core::result::Result<gpui::app::entity_map::Model<terminal::Terminal>, anyhow::Error>, gpui::app::async_context::{impl#3}::update_model::{closure_env#0}<project::Project, core::result::Result<gpui::app::entity_map::Model<terminal::Terminal>, anyhow::Error>, terminal_view::{impl#7}::deserialize::{closure#0}::{async_block#0}::{closure_env#1}>> () at crates/gpui/src/window.rs:4483
#25 0x000055555b186ca7 in gpui::app::async_context::{impl#3}::update_model<project::Project, core::result::Result<gpui::app::entity_map::Model<terminal::Terminal>, anyhow::Error>, terminal_view::{impl#7}::deserialize::{closure#0}::{async_block#0}::{closure_env#1}> ()
    at crates/gpui/src/app/async_context.rs:335
#26 0x000055555b18829f in gpui::app::entity_map::Model::update<project::Project, gpui::app::async_context::AsyncWindowContext, core::result::Result<gpui::app::entity_map::Model<terminal::Terminal>, anyhow::Error>, terminal_view::{impl#7}::deserialize::{closure#0}::{async_block#0}::{closure_env#1}>
    () at crates/gpui/src/app/entity_map.rs:414
#27 0x000055555b13e393 in terminal_view::{impl#7}::deserialize::{closure#0}::{async_block#0} () at crates/terminal_view/src/terminal_view.rs:903
#28 0x000055555b19a759 in core::future::future::{impl#1}::poll<alloc::boxed::Box<dyn core::future::future::Future<Output=core::result::Result<gpui::view::View<terminal_view::TerminalView>, anyhow::Error>>, alloc::alloc::Global>> ()
    at /rustc/791adf759cc065316f054961875052d5bc03e16c/library/core/src/future/future.rs:123
#29 0x000055555b1b761f in async_task::runnable::{impl#6}::spawn_local::{impl#1}::poll<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output=core::result::Result<gpui::view::View<terminal_view::TerminalView>, anyhow::Error>>, alloc::alloc::Global>>> ()
    at /home/uni/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.7.0/src/runnable.rs:455
#30 0x000055555b144528 in async_task::raw::RawTask::run<async_task::runnable::{impl#6}::spawn_local::Checked<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output=core::result::Result<gpui::view::View<terminal_view::TerminalView>, anyhow::Error>>, alloc::alloc::Global>>>, core::result::Result<gpui::view::View<terminal_view::TerminalView>, anyhow::Error>, gpui::executor::{impl#6}::spawn::inner::{closure_env#0}<core::result::Result<gpui::view::View<terminal_view::TerminalView>, anyhow::Error>>, ()> ()
    at /home/uni/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.7.0/src/raw.rs:557
#31 0x000055556099638b in async_task::runnable::Runnable::run<()> ()
    at /home/uni/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.7.0/src/runnable.rs:781
#32 0x000055555efd702d in gpui::platform::linux::wayland::client::{impl#3}::new::{closure#1} ()
    at crates/gpui/src/platform/linux/wayland/client.rs:324
#33 0x000055555edc8a35 in calloop::sources::{impl#4}::process_events::{closure#0}<gpui::platform::linux::wayland::client::WaylandClientStatePtr, calloop::sources::channel::Channel<async_task::runnable::Runnable<()>>, gpui::platform::linux::wayland::client::{impl#3}::new::{closure_env#1}> ()
    at /home/uni/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.12.4/src/sources/mod.rs:327
#34 0x000055555ee1213e in calloop::sources::channel::{impl#7}::process_events::{closure#0}<async_task::runnable::Runnable<()>, calloop::sources::{impl#4}::process_events::{closure_env#0}<gpui::platform::linux::wayland::client::WaylandClientStatePtr, calloop::sources::channel::Channel<async_task::runnable::Runnable<()>>, gpui::platform::linux::wayland::client::{impl#3}::new::{closure_env#1}>> ()
    at /home/uni/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.12.4/src/sources/channel.rs:187
#35 0x000055555f0dc7f4 in calloop::sources::ping::eventfd::{impl#1}::process_events::{closure#0}<calloop::sources::channel::{impl#7}::process_events::{closure_env#0}<async_task::runnable::Runnable<()>, calloop::sources::{impl#4}::process_events::{closure_env#0}<gpui::platform::linux::wayland::client::WaylandClientStatePtr, calloop::sources::channel::Channel<async_task::runnable::Runnable<()>>, gpui::platform::linux::wayland::client::{impl#3}::new::{closure_env#1}>>> () at /home/uni/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.12.4/src/sources/ping/eventfd.rs:138
#36 0x000055555edf4518 in calloop::sources::generic::{impl#12}::process_events<calloop::sources::ping::eventfd::ArcAsFd, std::io::error::Error, calloop::sources::ping::eventfd::{impl#1}::process_events::{closure_env#0}<calloop::sources::channel::{impl#7}::process_events::{closure_env#0}<async_task::runnable::Runnable<()>, calloop::sources::{impl#4}::process_events::{closure_env#0}<gpui::platform::linux::wayland::client::WaylandClientStatePtr, calloop::sources::channel::Channel<async_task::runnable::Runnable<()>>, gpui::platform::linux::wayland::client::{impl#3}::new::{closure_env#1}>>>> ()
    at /home/uni/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.12.4/src/sources/generic.rs:290
#37 0x000055555f0dc069 in calloop::sources::ping::eventfd::{impl#1}::process_events<calloop::sources::channel::{impl#7}::process_events::{closure_env#0}<async_task::runnable::Runnable<()>, calloop::sources::{impl#4}::process_events::{closure_env#0}<gpui::platform::linux::wayland::client::WaylandClientStatePtr, calloop::sources::channel::Channel<async_task::runnable::Runnable<()>>, gpui::platform::linux::wayland::client::{impl#3}::new::{closure_env#1}>>> () at /home/uni/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.12.4/src/sources/ping/eventfd.rs:127
#38 0x000055555ee11e56 in calloop::sources::channel::{impl#7}::process_events<async_task::runnable::Runnable<()>, calloop::sources::{impl#4}::process_events::{closure_env#0}<gpui::platform::linux::wayland::client::WaylandClientStatePtr, calloop::sources::channel::Channel<async_task::runnable::Runnable<()>>, gpui::platform::linux::wayland::client::{impl#3}::new::{closure_env#1}>> ()
    at /home/uni/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.12.4/src/sources/channel.rs:184
#39 0x000055555ee9e4d3 in calloop::sources::{impl#4}::process_events<gpui::platform::linux::wayland::client::WaylandClientStatePtr, calloop::sources::channel::Channel<async_task::runnable::Runnable<()>>, gpui::platform::linux::wayland::client::{impl#3}::new::{closure_env#1}> ()
    at /home/uni/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.12.4/src/sources/mod.rs:326
#40 0x000055555ebc2570 in calloop::loop_logic::EventLoop::dispatch_events<gpui::platform::linux::wayland::client::WaylandClientStatePtr> ()
    at /home/uni/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.12.4/src/loop_logic.rs:445
#41 0x000055555ebcbe41 in calloop::loop_logic::EventLoop::dispatch<gpui::platform::linux::wayland::client::WaylandClientStatePtr, core::option::Option<core::time::Duration>> () at /home/uni/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.12.4/src/loop_logic.rs:559
#42 0x000055555ebc9fe7 in calloop::loop_logic::EventLoop::run<gpui::platform::linux::wayland::client::WaylandClientStatePtr, gpui::platform::linux::wayland::client::{impl#4}::run::{closure_env#0}, core::option::Option<core::time::Duration>> ()
    at /home/uni/.cargo/registry/src/index.crates.io-6f17d22bba15001f/calloop-0.12.4/src/loop_logic.rs:596
#43 0x000055555f05e6b3 in gpui::platform::linux::wayland::client::{impl#4}::run () at crates/gpui/src/platform/linux/wayland/client.rs:494
#44 0x000055555efd51e2 in gpui::platform::linux::platform::{impl#1}::run<gpui::platform::linux::wayland::client::WaylandClient> ()
    at crates/gpui/src/platform/linux/platform.rs:129
#45 0x000055555913139b in gpui::app::App::run<Zed::main::{closure_env#3}> () at crates/gpui/src/app.rs:140
#46 0x000055555926a8b9 in Zed::main () at crates/zed/src/main.rs:332
```

</details>

### Environment

todo

**Comment by apricotbucket28** [comment]
https://github.com/zed-industries/zed/pull/12687 has been merged
