### ISSUE TITLE
Failed to build on Windows

### ISSUE THREAD

**Issue by Ardub92** [zed-industries/zed#12768]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I followed [this guide](https://github.com/zed-industries/zed/blob/main/docs/src/development/windows.md), but I can't run zed for some reason.

Error:
```bash
error: failed to run custom build command for `live_kit_server v0.1.0 (E:\Projects\zed\crates\live_kit_server)`

Caused by:
  process didn't exit successfully: `E:\Projects\zed\target\debug\build\live_kit_server-0cdd89dba45ecfe5\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at crates\live_kit_server\build.rs:8:10:
  called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "protoc failed: C:\\Users\\������������\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\prost-build-0.9.0\\third-party\\protobuf\\include: warning: directory does not exist.\r\ngoogle/protobuf/timestamp.proto: File not found.\r\nlivekit_models.proto:8:1: Import \"google/protobuf/timestamp.proto\" was not found or had errors.\r\nlivekit_models.proto:267:3: \"google.protobuf.Timestamp\" is not defined.\r\nlivekit_models.proto:268:3: \"google.protobuf.Timestamp\" is not defined.\r\nlivekit_models.proto:312:3: \"google.protobuf.Timestamp\" is not defined.\r\nlivekit_models.proto:315:3: \"google.protobuf.Timestamp\" is not defined.\r\nlivekit_models.proto:321:3: \"google.protobuf.Timestamp\" is not defined.\r\nlivekit_models.proto:324:3: \"google.protobuf.Timestamp\" is not defined.\r\nlivekit_room.proto:8:1: Import \"livekit_models.proto\" was not found or had errors.\r\nlivekit_room.proto:67:3: \"AutoTrackEgress\" is not defined.\r\nlivekit_room.proto:76:12: \"Room\" is not defined.\r\nlivekit_room.proto:93:12: \"ParticipantInfo\" is not defined.\r\nlivekit_room.proto:117:3: \"TrackInfo\" is not defined.\r\nlivekit_room.proto:126:3: \"ParticipantPermission\" is not defined.\r\nlivekit_room.proto:137:12: \"ParticipantTracks\" is not defined.\r\nlivekit_room.proto:147:3: \"DataPacket.Kind\" is not defined.\r\nlivekit_room.proto:16:46: \"Room\" is not defined.\r\nlivekit_room.proto:29:56: \"ParticipantInfo\" is not defined.\r\nlivekit_room.proto:38:60: \"ParticipantInfo\" is not defined.\r\nlivekit_room.proto:47:63: \"Room\" is not defined.\r\n" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

### Environment

N/A

**Comment by osiewicz** [comment]
Just a hunch, it looks like your user name contains unprintable characters; could you try to clone zed into some other directory than `C:\Users`?

**Comment by osiewicz** [comment]
Oh, nevermind, you've cloned it to "E:\" and it's the cargo registry that we're referencing.

**Comment by Ardub92** [comment]
> Oh, nevermind, you've cloned it to "E:" and it's the cargo registry that we're referencing. What is the sha1 of commit you're trying to build?

`5f5e6b8616a256e80d9db7b286759ce668ef81fc`

**Comment by Ardub92** [comment]
@osiewicz Any updates?

**Comment by osiewicz** [comment]
No, I did not look into it further. If you do have non-ascii characters in your user name, I'd suggest trying to [patch prost-build](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section) so that it's not in C:\Users.

**Comment by tibitTW** [comment]
same problem here

```sh
error: failed to run custom build command for `live_kit_server v0.1.0 (D:\zed\crates\live_kit_server)`
 
Caused by:
  process didn't exit successfully: `D:\zed\target\release\build\live_kit_server-13995be543601fc7\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at crates\live_kit_server\build.rs:8:10:
  called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "protoc failed: C:\\Users\\LouisLi���n�~\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\prost-build-0.9.0\\third-party\\protobuf\\include: warning: directory does not exist.\r\ngoogle/protobuf/timestamp.proto: File not found.\r\nlivekit_models.proto:8:1: Import \"google/protobuf/timestamp.proto\" was not found or had errors.\r\nlivekit_models.proto:267:3: \"google.protobuf.Timestamp\" is not defined.\r\nlivekit_models.proto:268:3: \"google.protobuf.Timestamp\" is not defined.\r\nlivekit_models.proto:312:3: \"google.protobuf.Timestamp\" is not defined.\r\nlivekit_models.proto:315:3: \"google.protobuf.Timestamp\" is not defined.\r\nlivekit_models.proto:321:3: \"google.protobuf.Timestamp\" is not defined.\r\nlivekit_models.proto:324:3: \"google.protobuf.Timestamp\" is not defined.\r\nlivekit_room.proto:8:1: Import \"livekit_models.proto\" was not found or had errors.\r\nlivekit_room.proto:67:3: \"AutoTrackEgress\" is not defined.\r\nlivekit_room.proto:76:12: \"Room\" is not defined.\r\nlivekit_room.proto:93:12: \"ParticipantInfo\" is not defined.\r\nlivekit_room.proto:117:3: \"TrackInfo\" is not defined.\r\nlivekit_room.proto:126:3: \"ParticipantPermission\" is not defined.\r\nlivekit_room.proto:137:12: \"ParticipantTracks\" is not defined.\r\nlivekit_room.proto:147:3: \"DataPacket.Kind\" is not defined.\r\nlivekit_room.proto:16:46: \"Room\" is not defined.\r\nlivekit_room.proto:29:56: \"ParticipantInfo\" is not defined.\r\nlivekit_room.proto:38:60: \"ParticipantInfo\" is not defined.\r\nlivekit_room.proto:47:63: \"Room\" is not defined.\r\n" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by SomeoneToIgnore** [comment]
Both of you seem to have `�` in your user directory, I wonder if that's the cause.

**Comment by tibitTW** [comment]
@Ardub92 I found a workaround and I can build Zed now, just change the cargo working directory to a path without non-ascii characters, this is my setup:

add a new environment variable `CARGO_HOME`=`C:\`

**Comment by SomeoneToIgnore** [comment]
To add on top: 
* Zed is planning to go away from this particular build script (not sure if the other one will handle such cases better, though): https://github.com/zed-industries/zed/actions/runs/12077190641?pr=20826
* The failing script belongs to LiveKit and should be addressed on their side, we do not own the corresponding code
