### ISSUE TITLE
Linux/X11-Ubuntu 22.04 - fails to build from source, Compose:39:34: string literal is not a valid UTF-8 string

### ISSUE THREAD

**Issue by elcuco** [zed-industries/zed#13463]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Running a build from source, for several weeks. 2-3 weeks ago it just fails to start. I see this on the console:

```
diego   main ?:1  ~/src/github/zed  130  RUST_BACKTRACE=1  ./target/debug/zed
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:39:34: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:40:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:41:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:42:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:43:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:44:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:45:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:46:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:47:27: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:48:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:49:29: string literal is not a valid UTF-8 string
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:49:29: too many errors
xkbcommon: ERROR: /usr/share/X11/locale/iso8859-1/Compose:49:29: failed to parse file
[2024-06-24T14:46:29+03:00 ERROR util] crates/gpui/src/platform/linux/x11/client.rs:257: ()
thread 'main' panicked at crates/gpui/src/platform/linux/x11/client.rs:258:14:
called `Option::unwrap()` on a `None` value
stack backtrace:
0: rust_begin_unwind
at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
1: core::panicking::panic_fmt
at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
2: core::panicking::panic
at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:146:5
3: core::option::unwrap_failed
at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/option.rs:1984:5
4: core::option::Option<T>::unwrap
at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/option.rs:932:21
5: gpui::platform::linux::x11::client::X11Client::new
at ./crates/gpui/src/platform/linux/x11/client.rs:252:25
6: gpui::platform::current_platform
at ./crates/gpui/src/platform.rs:75:26
7: gpui::app::App::new
at ./crates/gpui/src/app.rs:116:13
8: zed::main
at ./crates/zed/src/main.rs:296:15
9: core::ops::function::FnOnce::call_once
at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Relevant lines from the X11 locale (passed through `nl` to get line numbers):
``` x11 config
38  <Multi_key> <space> <minus>             : "~"   asciitilde
39  <Multi_key> <exclam> <exclam>           : "\241"        exclamdown
40  <Multi_key> <c> <slash>                 : "\242"        cent
41  <Multi_key> <slash> <c>                 : "\242"        cent
42  <Multi_key> <C> <slash>                 : "\242"        cent
43  <Multi_key> <slash> <C>                 : "\242"        cent
```

Yes, these are not UTF8 values.

### Environment

```
diego   4236-cmodbusini-upsertmeter-does-not-check-for-errors {16} ?:1  ~/src/tigo/ManagementUnit  lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.

`/home/diego/.local/share/zed/` - don't see logs there. I also deleted this directory completely - still no go.

**Comment by nt8r** [comment]
This can probably be worked around by using a UTF-8 locale; it seems that your current locale is probably something like "en_US" as opposed to "en_US.utf-8".

Of course, that doesn't invalidate the bug--but

**Comment by elcuco** [comment]
> This can probably be worked around by using a UTF-8 locale; it seems that your current locale is probably something like "en_US" (which maps to "en_US.iso-8859-1") as opposed to "en_US.UTF-8".
> 
> Of course, that doesn't invalidate the bug. That said, upstream xkbcommon also appears to lack support for non-UTF-8 locales as `xkbcli compile-compose --file=/usr/share/X11/locale/iso8859-1/Compose` gives the same error messages. It appears this is actually [by design](https://github.com/xkbcommon/libxkbcommon/issues/76), so the workaround of selecting a UTF-8 locale is probably the only option.

Well... I tried to set `LC_ALL=C` and running zed. But still does not work. Also;

https://github.com/zed-industries/zed/blob/8949460bd7f18b44f60bcb435b5487b50e9d8811/crates/gpui/src/platform/linux/x11/client.rs#L252-L260

It seems that the code is already trying to load the code using 'ASCII' locale. I hope this helps narrowing the issue down.

**Comment by elcuco** [comment]
Tested again with `en_US.UTF-8`, this overcomes the issue. Now zed is crashing for another problem:

```
diego   main ?:1  ~/src/github/zed  101  LC_CTYPE=en_US.UTF-8 ./target/debug/zed 
Thread "<unnamed>" panicked with "Could not start file watcher: Error { kind: Io(Os { code: 24, kind: Uncategorized, message: \"Too many open files\" }), paths: [] }" at crates/fs/src/fs.rs:482:10
0: zed::
```

A workaround is found, but the issue is still valid.
