### ISSUE TITLE
Zed freezing my enviroment

### ISSUE THREAD

**Issue by dayves** [zed-industries/zed#14519]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

The screen frequently freezes, causing all visual elements on my laptop to become unresponsive for a few seconds. However, it seems to be only a visual freeze, bacause when I use ctrl+tab, for example, it's change the app tab, after the screen freeze.
Same bug on zed 0.143.6 and 0.143.7

### Environment

![image](https://github.com/user-attachments/assets/3547c8bf-f655-4556-85ed-8adc63e260d4)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

[Zed.log](https://github.com/user-attachments/files/16240426/Zed.log)

</pre></details>

**Comment by betancour** [comment]
Same thing happens in my environment. When using hybrid mode with both GPUs, everything works flawlessly. However, when I switch to using only the integrated graphics, the Zed Editor starts consuming a lot of CPU and my computer freezes. So, I can relate to the person who reported this issue. I am using an Nvidia graphics card.


![Screenshot from 2024-07-15 21-10-57](https://github.com/user-attachments/assets/757ee600-136a-46c6-84a1-99e4fc49fb62)

**Comment by notpeter** [comment]
Of note, both your laptops have an Nvidia Geforce RTX 3050 GPU.

**Comment by ConradIrwin** [comment]
@dayves Can you confirm if the graphics mode is what causes this? 

If so, this might be another GPU compatibility issue

**Comment by betancour** [comment]
> @dayves Can you confirm if the graphics mode is what causes this?
> 
> If so, this might be another GPU compatibility issue


Conrad, I'd like to point out that the issue occurs exclusively when using Wayland. When I switch to X, this problem doesn't arise.

**Comment by ConradIrwin** [comment]
Weird. Do you know why that would cause a difference?

**Comment by betancour** [comment]
> Weird. Do you know why that would cause a difference?


It might be a GPU issue. The GPU shows usage by the app, but since my CPU usage spikes due to Zed, I'm wondering how to debug this. It likely has to do with how Wayland handles GPU calls. When using hybrid mode, the integrated GPU on CPU works fine. It also works with NVIDIA Prime, so I'm trying to figure out what the problem could be.

**Comment by dayves** [comment]
@ConradIrwin I trying on another DE, and distro, and now it's working fine, but this time my Nvidia gpu is disabled. Now I'm using Popos

**Comment by pro-khar** [comment]
Hey @betancour .  I'm on Xorg (X11)

**Comment by snoopdouglas** [comment]
Just encountered this on Xorg too. The issue only seems to occur when opening Zed on an external display. No errors are shown in any logs that I can see.

**Comment by Vanuan** [comment]
Could be a duplicate of this:
https://github.com/zed-industries/zed/issues/7940

I've investigated the issue for a potential solution. PTAL: https://github.com/zed-industries/zed/issues/23288

**Comment by elsherif24** [comment]
## Steps to trigger the problem:
1. Fresh installation of vanilla Arch Linux.
2. Install zed using pacman package manager.
3. Use second monitor on a laptop with NVIDIA gpu.
4. Run zed on the second monitor (same issues happens when running it on main laptop monitor with second one connected).
5. Don't do any config or sign in just open the untitled file and make it a bit big 500000 lines.
6. switch between zed and other window (kitty terminal).
7. zed freezes the cursor and any visual thing.

https://github.com/user-attachments/assets/56eac85f-af7f-4752-8b6b-7bb644ff1774

## System specs:
Zed: v0.171.6 (Zed)
OS: Linux X11 arch unknown
Memory: 15 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GTX 1650 || NVIDIA || 565.77

![Image](https://github.com/user-attachments/assets/6389f6ba-0def-464f-abc5-583ce5f13c8d)

### This is the whole zed log file barbecue its a fresh installation only 292 lines.
<details><summary>Zed.log</summary>


```
2025-02-02T08:40:35.723496328+02:00 [INFO] ========== starting zed ==========
2025-02-02T08:40:35.78562965+02:00 [INFO] Compositor detection: _NET_WM_CM_S?=false, _NET_WM_CM_OWNER=false, _NET_SUPPORTING_WM_CHECK=true
2025-02-02T08:40:35.785700539+02:00 [INFO] x11: compositor present: true, gtk_frame_extents_supported: false
2025-02-02T08:40:35.812987878+02:00 [INFO] Presentation support: "VK_KHR_wayland_surface"
2025-02-02T08:40:35.813332754+02:00 [INFO] Presentation support: "VK_KHR_xcb_surface"
2025-02-02T08:40:35.813358386+02:00 [INFO] Presentation support: "VK_KHR_xlib_surface"
2025-02-02T08:40:35.813384158+02:00 [INFO] Enabling Vulkan Portability
2025-02-02T08:40:35.813406716+02:00 [INFO] Enabling color space support
2025-02-02T08:40:35.859074606+02:00 [INFO] Adapter: "NVIDIA GeForce GTX 1650"
2025-02-02T08:40:35.859133273+02:00 [INFO] No ray tracing extensions are supported
2025-02-02T08:40:35.965261716+02:00 [INFO] perform;
2025-02-02T08:40:35.965338611+02:00 [INFO] authenticate;
2025-02-02T08:40:35.966009157+02:00 [INFO] read_command;
2025-02-02T08:40:35.966689342+02:00 [INFO] send_secondary_commands;
2025-02-02T08:40:35.968109075+02:00 [INFO] socket reader;
2025-02-02T08:40:35.968343463+02:00 [INFO] new;
2025-02-02T08:40:35.980100684+02:00 [INFO] Opening main db
2025-02-02T08:40:35.994686199+02:00 [INFO] Opening main db
2025-02-02T08:40:36.000003774+02:00 [INFO] Using git binary path: None
2025-02-02T08:40:36.019083226+02:00 [INFO] set environment variables from shell:/usr/bin/fish, path:/home/elsherif/.local/share/JetBrains/Toolbox/scripts:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
2025-02-02T08:40:36.160986821+02:00 [INFO] No prompt template overrides directory found at /home/elsherif/.local/share/zed/prompt_overrides. Using built-in prompts.
2025-02-02T08:40:36.162812611+02:00 [INFO] No prompt template overrides directory found at /home/elsherif/.local/share/zed/prompt_overrides. Using built-in prompts.
2025-02-02T08:40:36.210616457+02:00 [INFO] activate is not implemented on Linux, ignoring the call
2025-02-02T08:40:36.214079467+02:00 [INFO] Opening main db
2025-02-02T08:40:36.218900751+02:00 [INFO] perform;
2025-02-02T08:40:36.219000554+02:00 [INFO] authenticate;
2025-02-02T08:40:36.220004104+02:00 [INFO] read_command;
2025-02-02T08:40:36.223256543+02:00 [INFO] socket reader;
2025-02-02T08:40:36.231929922+02:00 [WARN] Failed to watch: No such file or directory (os error 2) about ["/home/elsherif/.config/github-copilot"]
2025-02-02T08:40:36.232775211+02:00 [INFO] Using Visual { id: 654, colormap: 0, depth: 32 }
2025-02-02T08:40:36.232814253+02:00 [INFO] Creating colormap 25165827
2025-02-02T08:40:36.238266413+02:00 [INFO] Using surface present mode IMMEDIATE
2025-02-02T08:40:36.295724908+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2025-02-02T08:40:36.295773378+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2025-02-02T08:40:36.295800826+02:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2025-02-02T08:40:36.59536316+02:00 [INFO] Refreshing at 16666 micros
2025-02-02T08:40:36.595629884+02:00 [INFO] x11: no compositor present, falling back to server-side window decorations
2025-02-02T08:40:36.621972271+02:00 [INFO] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "NVIDIA GeForce GTX 1650", driver_name: "NVIDIA", driver_info: "565.77" }
2025-02-02T08:40:36.652984665+02:00 [WARN] GPU frame is out of date
2025-02-02T08:40:36.653068964+02:00 [WARN] Acquire failed because the surface is out of date
2025-02-02T08:40:36.65448744+02:00 [INFO] Using surface present mode IMMEDIATE
2025-02-02T08:40:36.654516983+02:00 [INFO] Retaining current format: Bgra8UnormSrgb
2025-02-02T08:40:36.680158862+02:00 [INFO] rebuilt extension index in 891.733µs
2025-02-02T08:40:36.684500476+02:00 [INFO] activate is not implemented on Linux, ignoring the call
2025-02-02T08:40:36.686817181+02:00 [INFO] Opening main db
2025-02-02T08:40:36.693817513+02:00 [ERROR] missing field `name` at line 17 column 1
2025-02-02T08:40:36.694032065+02:00 [ERROR] Is a directory (os error 21)
2025-02-02T08:40:38.890727395+02:00 [INFO] Using surface present mode IMMEDIATE
2025-02-02T08:40:38.890873853+02:00 [INFO] Retaining current format: Bgra8UnormSrgb
2025-02-02T08:40:39.178031816+02:00 [INFO] Node runtime install_if_needed
2025-02-02T08:40:40.472992827+02:00 [ERROR] missing field `name` at line 17 column 1
2025-02-02T08:40:41.203322174+02:00 [ERROR] missing field `name` at line 17 column 1
2025-02-02T08:40:42.250306677+02:00 [ERROR] missing field `name` at line 17 column 1
2025-02-02T08:40:56.144416345+02:00 [INFO] starting language server process. binary path: "/home/elsherif/.local/share/zed/node/node-v22.5.1-linux-x64/bin/node", working directory: "/", args: ["/home/elsherif/.local/share/zed/copilot/copilot-v0.7.0/dist/language-server.js", "--stdio"]
2025-02-02T08:40:56.930073666+02:00 [INFO] Language server with id 0 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[lsp] GitHub Copilot Language Server 1.236.0 initialized"
}
2025-02-02T08:40:56.930355014+02:00 [INFO] Language server with id 0 sent unhandled notification workspace/configuration:
{
  "items": [
    {
      "section": "github.copilot"
    },
    {
      "section": "github-enterprise"
    },
    {
      "section": "http"
    },
    {
      "section": "telemetry"
    }
  ]
}
2025-02-02T08:40:57.18396357+02:00 [INFO] Language server with id 0 sent unhandled notification window/logMessage:
{
  "type": 2,
  "message": "[certificates] Failed to parse certificate # ACCVRAIZ1\n Error: error:0480006C:PEM routines::no start line\n    at new X509Certificate (node:internal/crypto/x509:119:21)\n    at /home/elsherif/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:79:36\n    at Array.filter (<anonymous>)\n    at Cle.removeExpiredCertificates (/home/elsherif/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:77:32)\n    at Cle.getAllRootCAs (/home/elsherif/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:68:38)\n    at Rge.createSecureContext (/home/elsherif/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificates.ts:46:23)\n    at Rge.applyToRequestOptions (/home/elsherif/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificates.ts:61:23)\n    at Dge.fetch (/home/elsherif/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/helix.ts:90:9)\n    at Fee.fetchExperiments (/home/elsherif/.local/share/zed/copilot/copilot-v0.7.0/lib/src/experiments/fetchExperiments.ts:79:20) {\n  opensslErrorStack: [\n    'error:0688010A:asn1 encoding routines::nested asn1 error',\n    'error:06800066:asn1 encoding routines::bad object header',\n    'error:0680009B:asn1 encoding routines::too long'\n  ],\n  library: 'PEM routines',\n  reason: 'no start line',\n  code: 'ERR_OSSL_PEM_NO_START_LINE'\n}"
}
2025-02-02T08:40:57.184132028+02:00 [INFO] Language server with id 0 sent unhandled notification window/logMessage:
{
  "type": 2,
  "message": "[certificates] Failed to parse certificate # ACCVRAIZ1\n Error: error:0480006C:PEM routines::no start line\n    at new X509Certificate (node:internal/crypto/x509:119:21)\n    at /home/elsherif/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:79:36\n    at Array.filter (<anonymous>)\n    at Cle.removeExpiredCertificates (/home/elsherif/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:77:32)\n    at Cle.getAllRootCAs (/home/elsherif/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:68:38)\n    at Rge.createSecureContext (/home/elsherif/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificates.ts:46:23)\n    at Rge.applyToRequestOptions (/home/elsherif/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificates.ts:61:23)\n    at Dge.fetch (/home/elsherif/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/helix.ts:90:9)\n    at Fee.fetchExperiments (/home/elsherif/.local/share/zed/copilot/copilot-v0.7.0/lib/src/experiments/fetchExperiments.ts:79:20) {\n  opensslErrorStack: [\n    'error:0688010A:asn1 encoding routines::nested asn1 error',\n    'error:06800066:asn1 encoding routines::bad object header',\n    'error:0680009B:asn1 encoding routines::too long'\n  ],\n  library: 'PEM routines',\n  reason: 'no start line',\n  code: 'ERR_OSSL_PEM_NO_START_LINE'\n}"
}
2025-02-02T08:40:57.184286057+02:00 [INFO] Language server with id 0 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[certificates] Removed 2 expired certificates"
}
2025-02-02T08:40:58.054883073+02:00 [ERROR] missing field `name` at line 17 column 1
2025-02-02T08:41:05.225211976+02:00 [ERROR] missing field `name` at line 18 column 1
2025-02-02T08:41:09.396358575+02:00 [ERROR] missing field `name` at line 19 column 1
2025-02-02T08:41:09.793107352+02:00 [ERROR] missing field `name` at line 19 column 1
2025-02-02T08:41:10.361403925+02:00 [ERROR] missing field `name` at line 19 column 1
2025-02-02T08:41:13.81255731+02:00 [INFO] set status on client 0: Authenticating
2025-02-02T08:41:13.814012983+02:00 [INFO] perform;
2025-02-02T08:41:13.814083582+02:00 [INFO] authenticate;
2025-02-02T08:41:13.814157117+02:00 [INFO] read_command;
2025-02-02T08:41:13.814559533+02:00 [INFO] socket reader;
2025-02-02T08:41:13.915109301+02:00 [INFO] new;
2025-02-02T08:41:13.916628373+02:00 [ERROR] Failed to open with dbus: A portal frontend implementing `org.freedesktop.portal.OpenURI` was not found
2025-02-02T08:41:16.624724325+02:00 [INFO] Using surface present mode IMMEDIATE
2025-02-02T08:41:16.624774119+02:00 [INFO] Retaining current format: Bgra8UnormSrgb
2025-02-02T08:41:26.428270759+02:00 [INFO] Using surface present mode IMMEDIATE
2025-02-02T08:41:26.428350594+02:00 [INFO] Retaining current format: Bgra8UnormSrgb
2025-02-02T08:41:37.603235864+02:00 [INFO] set status on client 0: Reauthenticating
2025-02-02T08:41:37.603750801+02:00 [ERROR] authentication canceled
2025-02-02T08:41:37.604772356+02:00 [INFO] perform;
2025-02-02T08:41:37.604933261+02:00 [INFO] authenticate;
2025-02-02T08:41:37.605106188+02:00 [INFO] read_command;
2025-02-02T08:41:37.605866396+02:00 [INFO] socket reader;
2025-02-02T08:41:37.784334038+02:00 [INFO] new;
2025-02-02T08:41:37.785697043+02:00 [ERROR] Failed to open with dbus: A portal frontend implementing `org.freedesktop.portal.OpenURI` was not found
2025-02-02T08:41:38.203583124+02:00 [INFO] Using surface present mode IMMEDIATE
2025-02-02T08:41:38.20365889+02:00 [INFO] Retaining current format: Bgra8UnormSrgb
2025-02-02T08:41:43.407597631+02:00 [INFO] Using surface present mode IMMEDIATE
2025-02-02T08:41:43.407746488+02:00 [INFO] Retaining current format: Bgra8UnormSrgb
2025-02-02T08:41:49.336898298+02:00 [ERROR] window not found
2025-02-02T08:41:49.337073057+02:00 [ERROR] window not found
2025-02-03T15:19:20.324381011+02:00 [INFO] ========== starting zed ==========
2025-02-03T15:19:20.334577436+02:00 [INFO] Compositor detection: _NET_WM_CM_S?=false, _NET_WM_CM_OWNER=false, _NET_SUPPORTING_WM_CHECK=true
2025-02-03T15:19:20.334673752+02:00 [INFO] x11: compositor present: true, gtk_frame_extents_supported: false
2025-02-03T15:19:20.363191012+02:00 [INFO] Presentation support: "VK_KHR_wayland_surface"
2025-02-03T15:19:20.363259809+02:00 [INFO] Presentation support: "VK_KHR_xcb_surface"
2025-02-03T15:19:20.363308002+02:00 [INFO] Presentation support: "VK_KHR_xlib_surface"
2025-02-03T15:19:20.363356684+02:00 [INFO] Enabling Vulkan Portability
2025-02-03T15:19:20.363399569+02:00 [INFO] Enabling color space support
2025-02-03T15:19:20.403747202+02:00 [INFO] Adapter: "NVIDIA GeForce GTX 1650"
2025-02-03T15:19:20.403831505+02:00 [INFO] No ray tracing extensions are supported
2025-02-03T15:19:20.517788307+02:00 [INFO] perform;
2025-02-03T15:19:20.517915704+02:00 [INFO] authenticate;
2025-02-03T15:19:20.518021728+02:00 [INFO] Opening main db
2025-02-03T15:19:20.518112806+02:00 [INFO] read_command;
2025-02-03T15:19:20.518255848+02:00 [INFO] send_secondary_commands;
2025-02-03T15:19:20.518848271+02:00 [INFO] new;
2025-02-03T15:19:20.518952339+02:00 [INFO] socket reader;
2025-02-03T15:19:20.519951538+02:00 [INFO] Opening main db
2025-02-03T15:19:20.524973236+02:00 [INFO] Using git binary path: None
2025-02-03T15:19:20.541674023+02:00 [INFO] set environment variables from shell:/usr/bin/fish, path:/home/elsherif/.local/share/JetBrains/Toolbox/scripts:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
2025-02-03T15:19:20.611736126+02:00 [INFO] No prompt template overrides directory found at /home/elsherif/.local/share/zed/prompt_overrides. Using built-in prompts.
2025-02-03T15:19:20.612199825+02:00 [INFO] No prompt template overrides directory found at /home/elsherif/.local/share/zed/prompt_overrides. Using built-in prompts.
2025-02-03T15:19:20.650006018+02:00 [INFO] activate is not implemented on Linux, ignoring the call
2025-02-03T15:19:20.653308976+02:00 [INFO] Opening main db
2025-02-03T15:19:20.655554485+02:00 [INFO] perform;
2025-02-03T15:19:20.655629428+02:00 [INFO] authenticate;
2025-02-03T15:19:20.655724347+02:00 [INFO] read_command;
2025-02-03T15:19:20.656428592+02:00 [INFO] socket reader;
2025-02-03T15:19:20.658361126+02:00 [INFO] installing extension html latest version
2025-02-03T15:19:20.659359487+02:00 [INFO] Using Visual { id: 654, colormap: 0, depth: 32 }
2025-02-03T15:19:20.659459155+02:00 [INFO] Creating colormap 27262979
2025-02-03T15:19:20.665757824+02:00 [INFO] Using surface present mode IMMEDIATE
2025-02-03T15:19:20.730713997+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2025-02-03T15:19:20.730758837+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2025-02-03T15:19:20.730784959+02:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2025-02-03T15:19:20.78751356+02:00 [INFO] Refreshing at 16666 micros
2025-02-03T15:19:20.787746982+02:00 [INFO] x11: no compositor present, falling back to server-side window decorations
2025-02-03T15:19:20.789454895+02:00 [INFO] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "NVIDIA GeForce GTX 1650", driver_name: "NVIDIA", driver_info: "565.77" }
2025-02-03T15:19:20.827106661+02:00 [WARN] GPU frame is out of date
2025-02-03T15:19:20.827226655+02:00 [WARN] Acquire failed because the surface is out of date
2025-02-03T15:19:20.828464653+02:00 [INFO] Using surface present mode IMMEDIATE
2025-02-03T15:19:20.828518293+02:00 [INFO] Retaining current format: Bgra8UnormSrgb
2025-02-03T15:19:20.849034349+02:00 [INFO] activate is not implemented on Linux, ignoring the call
2025-02-03T15:19:20.850150119+02:00 [INFO] Opening main db
2025-02-03T15:19:20.851640397+02:00 [INFO] Opening main db
2025-02-03T15:19:21.091594142+02:00 [INFO] Node runtime install_if_needed
2025-02-03T15:19:21.389250082+02:00 [INFO] starting language server process. binary path: "/home/elsherif/.local/share/zed/node/node-v22.5.1-linux-x64/bin/node", working directory: "/", args: ["/home/elsherif/.local/share/zed/copilot/copilot-v0.7.0/dist/language-server.js", "--stdio"]
2025-02-03T15:19:22.166690688+02:00 [INFO] Language server with id 0 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[lsp] GitHub Copilot Language Server 1.236.0 initialized"
}
2025-02-03T15:19:22.166826466+02:00 [INFO] Language server with id 0 sent unhandled notification workspace/configuration:
{
  "items": [
    {
      "section": "github.copilot"
    },
    {
      "section": "github-enterprise"
    },
    {
      "section": "http"
    },
    {
      "section": "telemetry"
    }
  ]
}
2025-02-03T15:19:22.934906095+02:00 [INFO] rebuilt extension index in 2.928587ms
2025-02-03T15:19:22.935152228+02:00 [INFO] extensions updated. loading 1, reloading 0, unloading 0
2025-02-03T15:20:27.15566426+02:00 [INFO] Using surface present mode IMMEDIATE
2025-02-03T15:20:27.15583321+02:00 [INFO] Retaining current format: Bgra8UnormSrgb
2025-02-03T15:22:37.70528494+02:00 [INFO] ignoring macOS specific set_edited
2025-02-03T15:24:32.234473423+02:00 [INFO] Using surface present mode IMMEDIATE
2025-02-03T15:24:32.234648094+02:00 [INFO] Retaining current format: Bgra8UnormSrgb
2025-02-03T15:28:08.922094356+02:00 [INFO] Using surface present mode IMMEDIATE
2025-02-03T15:28:08.922266512+02:00 [INFO] Retaining current format: Bgra8UnormSrgb
2025-02-03T15:28:37.076061185+02:00 [INFO] Using surface present mode IMMEDIATE
2025-02-03T15:28:37.076158263+02:00 [INFO] Retaining current format: Bgra8UnormSrgb
2025-02-03T15:30:25.77058561+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2025-02-03T15:30:25.785940893+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2025-02-03T15:30:25.798255961+02:00 [INFO] Creating a descriptor pool for at most 256 sets
2025-02-03T15:30:25.811354636+02:00 [INFO] Creating a descriptor pool for at most 256 sets
2025-02-03T15:33:13.734540124+02:00 [INFO] ignoring macOS specific set_edited
2025-02-03T15:33:14.667636936+02:00 [ERROR] window not found
2025-02-03T15:33:14.667745886+02:00 [ERROR] window not found
2025-02-03T15:45:42.076513955+02:00 [INFO] ========== starting zed ==========
2025-02-03T15:45:42.087950124+02:00 [INFO] Compositor detection: _NET_WM_CM_S?=false, _NET_WM_CM_OWNER=false, _NET_SUPPORTING_WM_CHECK=true
2025-02-03T15:45:42.088049929+02:00 [INFO] x11: compositor present: true, gtk_frame_extents_supported: false
2025-02-03T15:45:42.108878615+02:00 [INFO] Presentation support: "VK_KHR_wayland_surface"
2025-02-03T15:45:42.108947619+02:00 [INFO] Presentation support: "VK_KHR_xcb_surface"
2025-02-03T15:45:42.1089956+02:00 [INFO] Presentation support: "VK_KHR_xlib_surface"
2025-02-03T15:45:42.10904428+02:00 [INFO] Enabling Vulkan Portability
2025-02-03T15:45:42.109086675+02:00 [INFO] Enabling color space support
2025-02-03T15:45:42.134691937+02:00 [INFO] Adapter: "NVIDIA GeForce GTX 1650"
2025-02-03T15:45:42.134768764+02:00 [INFO] No ray tracing extensions are supported
2025-02-03T15:45:42.236428675+02:00 [INFO] Opening main db
2025-02-03T15:45:42.236503266+02:00 [INFO] perform;
2025-02-03T15:45:42.236623395+02:00 [INFO] authenticate;
2025-02-03T15:45:42.236776559+02:00 [INFO] read_command;
2025-02-03T15:45:42.236916871+02:00 [INFO] send_secondary_commands;
2025-02-03T15:45:42.237271111+02:00 [INFO] new;
2025-02-03T15:45:42.237332153+02:00 [INFO] Opening main db
2025-02-03T15:45:42.237392636+02:00 [INFO] socket reader;
2025-02-03T15:45:42.239800585+02:00 [INFO] Using git binary path: None
2025-02-03T15:45:42.25927105+02:00 [INFO] set environment variables from shell:/usr/bin/fish, path:/home/elsherif/.local/share/JetBrains/Toolbox/scripts:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
2025-02-03T15:45:42.271871768+02:00 [INFO] No prompt template overrides directory found at /home/elsherif/.local/share/zed/prompt_overrides. Using built-in prompts.
2025-02-03T15:45:42.272279856+02:00 [INFO] No prompt template overrides directory found at /home/elsherif/.local/share/zed/prompt_overrides. Using built-in prompts.
2025-02-03T15:45:42.285317995+02:00 [INFO] extensions updated. loading 1, reloading 0, unloading 0
2025-02-03T15:45:42.287263449+02:00 [INFO] activate is not implemented on Linux, ignoring the call
2025-02-03T15:45:42.289227481+02:00 [INFO] Opening main db
2025-02-03T15:45:42.291956006+02:00 [INFO] perform;
2025-02-03T15:45:42.29202948+02:00 [INFO] authenticate;
2025-02-03T15:45:42.292120135+02:00 [INFO] read_command;
2025-02-03T15:45:42.29279069+02:00 [INFO] socket reader;
2025-02-03T15:45:42.295228531+02:00 [INFO] Using Visual { id: 654, colormap: 0, depth: 32 }
2025-02-03T15:45:42.295305637+02:00 [INFO] Creating colormap 23068675
2025-02-03T15:45:42.300632431+02:00 [INFO] Using surface present mode IMMEDIATE
2025-02-03T15:45:42.358658436+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2025-02-03T15:45:42.35872744+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2025-02-03T15:45:42.358776609+02:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2025-02-03T15:45:42.417134016+02:00 [INFO] Refreshing at 16666 micros
2025-02-03T15:45:42.417231795+02:00 [INFO] x11: no compositor present, falling back to server-side window decorations
2025-02-03T15:45:42.418443836+02:00 [INFO] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "NVIDIA GeForce GTX 1650", driver_name: "NVIDIA", driver_info: "565.77" }
2025-02-03T15:45:42.443246682+02:00 [WARN] GPU frame is out of date
2025-02-03T15:45:42.44333587+02:00 [WARN] Acquire failed because the surface is out of date
2025-02-03T15:45:42.444248359+02:00 [INFO] Using surface present mode IMMEDIATE
2025-02-03T15:45:42.444273572+02:00 [INFO] Retaining current format: Bgra8UnormSrgb
2025-02-03T15:45:42.465564264+02:00 [INFO] activate is not implemented on Linux, ignoring the call
2025-02-03T15:45:42.466727206+02:00 [INFO] Opening main db
2025-02-03T15:45:42.472523828+02:00 [INFO] Opening main db
2025-02-03T15:45:42.737789478+02:00 [INFO] Node runtime install_if_needed
2025-02-03T15:45:42.843996953+02:00 [INFO] starting language server process. binary path: "/home/elsherif/.local/share/zed/node/node-v22.5.1-linux-x64/bin/node", working directory: "/", args: ["/home/elsherif/.local/share/zed/copilot/copilot-v0.7.0/dist/language-server.js", "--stdio"]
2025-02-03T15:45:43.663269434+02:00 [INFO] Language server with id 0 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[lsp] GitHub Copilot Language Server 1.236.0 initialized"
}
2025-02-03T15:45:43.663482244+02:00 [INFO] Language server with id 0 sent unhandled notification workspace/configuration:
{
  "items": [
    {
      "section": "github.copilot"
    },
    {
      "section": "github-enterprise"
    },
    {
      "section": "http"
    },
    {
      "section": "telemetry"
    }
  ]
}
2025-02-03T15:46:55.368520308+02:00 [INFO] Using Visual { id: 654, colormap: 0, depth: 32 }
2025-02-03T15:46:55.368682481+02:00 [INFO] Creating colormap 23068705
2025-02-03T15:46:55.37085282+02:00 [INFO] Using surface present mode IMMEDIATE
2025-02-03T15:46:55.442596905+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2025-02-03T15:46:55.44266528+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2025-02-03T15:46:55.442715427+02:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2025-02-03T15:46:55.497252274+02:00 [INFO] Refreshing at 16666 micros
2025-02-03T15:46:55.497659383+02:00 [INFO] x11: no compositor present, falling back to server-side window decorations
2025-02-03T15:46:55.498861153+02:00 [INFO] Using GPU: GpuSpecs { is_software_emulated: false, device_name: "NVIDIA GeForce GTX 1650", driver_name: "NVIDIA", driver_info: "565.77" }
2025-02-03T15:46:55.53025734+02:00 [WARN] GPU frame is out of date
2025-02-03T15:46:55.531234569+02:00 [INFO] Using surface present mode IMMEDIATE
2025-02-03T15:46:55.531343173+02:00 [INFO] Retaining current format: Bgra8UnormSrgb
2025-02-03T15:46:57.559829946+02:00 [INFO] activate is not implemented on Linux, ignoring the call
2025-02-03T15:47:01.20256848+02:00 [ERROR] window not found
2025-02-03T15:47:01.202636715+02:00 [ERROR] window not found

```
</details>

**Comment by simply-zaki** [comment]
same thing is happening to me too often

![Image](https://github.com/user-attachments/assets/0038cc71-b8c9-4c39-a172-b0e85b973e86)

**Comment by supun-io** [comment]
The same is happening to me on Ubuntu after waking the computer from sleep.

![Image](https://github.com/user-attachments/assets/932a8334-a615-4bbf-a975-e023bc6c94cf)

**Comment by notpeter** [comment]
I'm going to go ahead and close this as unactionable.  I think this is likely not distinct from the many other open issues about GPUs stability issues, there is a significant discussion and potential solutions outlined here:
- https://github.com/zed-industries/zed/issues/23288

We are hoping to prioritize work to improve this in the near future. Sorry you're seeing this and thanks for reporting.
