### ISSUE TITLE
Language server error: ruff/pyright oneshot canceled

### ISSUE THREAD

**Issue by tuto193** [zed-industries/zed#19268]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

`pyright` and `ruff` language servers crash/won't run anymore, and show the same crash log. Here is `pyright`'s:
```
Language server error: pyright

oneshot canceled
```

This very same setup was working without any problems 2 days ago. Restarting `zed` or my system does not make any difference.

Starting `zed .` in a `Python` project, attempts to start the language servers, but LSPs won't start even after manually restarting.

Only `pyright` will work, when _not_ using my local (system) binary (either at `/usr/bin/pyright` or with `home-manager` at `~/.nix-profile/bin/pyright`.
`ruff` will always crash regardless of the binary in use.

Other LSPs like `rust-analyzer`, or JSON's do still work without any problems.

### Environment

System:
  Kernel: 6.10.14-1-MANJARO arch: x86_64 bits: 64
  Desktop: KDE Plasma v: 6.2.0 Distro: Manjaro Linux
Machine:
  Type: Laptop System: LENOVO product: 82YU v: Lenovo V15 G4 AMN
    serial: <superuser required>
  Mobo: LENOVO model: LNVNB161216 v: NO DPK serial: <superuser required>
    UEFI: LENOVO v: L1CN32WW date: 06/14/2023
Battery:
  ID-1: BAT0 charge: 28.4 Wh (87.7%) condition: 32.4/38.0 Wh (85.2%)
CPU:
  Info: quad core model: AMD Ryzen 5 7520U with Radeon Graphics bits: 64
    type: MT MCP cache: L2: 2 MiB
  Speed (MHz): avg: 900 min/max: 900/6735 cores: 1: 900 2: 900 3: 900 4: 900
    5: 900 6: 900 7: 900 8: 900
Graphics:
  Device-1: Advanced Micro Devices [AMD/ATI] Mendocino driver: amdgpu
    v: kernel
  Device-2: Syntek Integrated Camera driver: uvcvideo type: USB
  Display: wayland server: X.org v: 1.21.1.13 with: Xwayland v: 24.1.3
    compositor: kwin_wayland driver: X: loaded: amdgpu unloaded: modesetting
    dri: radeonsi gpu: amdgpu resolution: 1: 1920x1080 2: 1920x1080
  API: EGL v: 1.5 drivers: kms_swrast,radeonsi,swrast
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.2.4-arch1.1
    renderer: AMD Radeon 610M (radeonsi raphael_mendocino LLVM 18.1.8 DRM 3.57
    6.10.14-1-MANJARO)
  API: Vulkan v: 1.3.295 drivers: radv surfaces: xcb,xlib,wayland
Audio:
  Device-1: Advanced Micro Devices [AMD/ATI] Rembrandt Radeon High Definition
    Audio driver: snd_hda_intel
  Device-2: Advanced Micro Devices [AMD] ACP/ACP3X/ACP6x Audio Coprocessor
    driver: snd_pci_acp6x
  Device-3: Advanced Micro Devices [AMD] Family 17h/19h HD Audio
    driver: snd_hda_intel
  API: ALSA v: k6.10.14-1-MANJARO status: kernel-api
  Server-1: PipeWire v: 1.2.5 status: active
Network:
  Device-1: MEDIATEK MT7921 802.11ax PCI Express Wireless Network Adapter
    driver: mt7921e
  IF: wlp2s0 state: up mac: <filter>
  Device-2: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  IF: enp3s0 state: down mac: <filter>
Bluetooth:
  Device-1: Foxconn / Hon Hai MediaTek Bluetooth Adapter driver: btusb
    type: USB
  Report: rfkill ID: hci0 rfk-id: 0 state: down bt-service: enabled,running
    rfk-block: hardware: no software: yes address: see --recommends
Drives:
  Local Storage: total: 953.87 GiB used: 56.42 GiB (5.9%)
  ID-1: /dev/nvme0n1 vendor: Emtec model: X300 1TB size: 953.87 GiB
Partition:
  ID-1: / size: 937.53 GiB used: 56.42 GiB (6.0%) fs: ext4 dev: /dev/dm-0
  ID-2: /boot/efi size: 299.4 MiB used: 448 KiB (0.1%) fs: vfat
    dev: /dev/nvme0n1p1
Swap:
  ID-1: swap-1 type: file size: 512 MiB used: 0 KiB (0.0%) file: /swapfile
Sensors:
  System Temperatures: cpu: 50.8 C mobo: 36.0 C gpu: amdgpu temp: 46.0 C
  Fan Speeds (rpm): N/A
Info:
  Memory: total: 16 GiB note: est. available: 13.48 GiB used: 7.7 GiB (57.1%)
  Processes: 315 Uptime: 4h 2m Shell: Zsh inxi: 3.3.36

### If applicable, add mockups / screenshots to help explain present your vision of the feature

Output from trying to debug it.
```
zeditor . --foreground
[2024-10-16T12:35:28+02:00 ERROR theme] theme not found: Colorizer Pro
[2024-10-16T12:35:28+02:00 ERROR workspace] No path or contents found for buffer
[2024-10-16T12:35:30+02:00 ERROR lsp] cannot read LSP message headers
[2024-10-16T12:35:30+02:00 ERROR lsp] Broken pipe (os error 32)
[2024-10-16T12:35:30+02:00 ERROR project::lsp_store] Failed to start language server "ruff": oneshot canceled
[2024-10-16T12:35:30+02:00 ERROR project::lsp_store] server stderr: "Ruff: An extremely fast Python linter and code formatter.\n\nUsage: ruff [OPTIONS] <COMMAND>\n\nCommands:\n  check    Run
 Ruff on the given files or directories (default)\n  rule     Explain a rule (or all rules)\n  config   List or describe the available configuration options\n  linter   List all supported up
stream linters\n  clean    Clear any caches in the current directory and any subdirectories\n  format   Run the Ruff formatter on the given files or directories\n  server   Run the language
server\n  version  Display Ruff's version\n  help     Print this message or the help of the given subcommand(s)\n\nOptions:\n  -h, --help     Print help\n  -V, --version  Print version\n\nLo
g levels:\n  -v, --verbose  Enable verbose logging\n  -q, --quiet    Print diagnostics, but nothing else\n  -s, --silent   Disable all logging (but still exit with status code \"1\" upon det
ecting\n                 diagnostics)\n\nGlobal options:\n      --config <CONFIG_OPTION>  Either a path to a TOML configuration file (`pyproject.toml` or\n                                `ru
ff.toml`), or a TOML `<KEY> = <VALUE>` pair (such as you might\n                                find in a `ruff.toml` configuration file) overriding a specific\n
   configuration option. Overrides of individual settings using this\n                                option always take precedence over all configuration files,\n
     including configuration files that were also specified using\n                                `--config`\n      --isolated                Ignore all configuration files\n\nFor help with
 a specific command, see: `ruff help <command>`.\n"
[2024-10-16T12:35:30+02:00 ERROR lsp] server shut down
```
Notice how it also says `"theme not found: Colorizer Pro"`. I already tried re-installing my colorscheme and the `ruff` extension, but this does not seem to help.

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary><pre>

2024-10-16T12:18:18.198513675+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:18.198541262+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:18.198570317+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:18.198597974+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:18.213542025+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-16T12:18:18.302347763+02:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-10-16T12:18:18.363512638+02:00 [INFO] fetching latest version of language server "pyright"
2024-10-16T12:18:18.381474847+02:00 [INFO] starting language server process. binary path: "/home/tuto/.nix-profile/bin/node", working directory: "/", args: ["/home/tuto/.local/share/zed/copilot/copilot-v0.5.0/dist/agent.js", "--stdio"]
2024-10-16T12:18:18.721715891+02:00 [INFO] add connection to peer
2024-10-16T12:18:18.72177358+02:00 [INFO] add_connection;
2024-10-16T12:18:18.721819048+02:00 [INFO] waiting for server hello
2024-10-16T12:18:18.770122006+02:00 [INFO] got server hello
2024-10-16T12:18:18.770183886+02:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 0 }, peer id: PeerId { owner_id: 582, id: 346114 })
2024-10-16T12:18:18.770247302+02:00 [INFO] set status on client 197031: Connected { peer_id: PeerId { owner_id: 582, id: 346114 }, connection_id: ConnectionId { owner_id: 0, id: 0 } }
2024-10-16T12:18:18.816554591+02:00 [INFO] set environment variables from shell:/usr/bin/zsh, path:/home/tuto/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/home/tuto/.cache/pypoetry/virtualenvs/opensight-network-ce-P5aor-py3.12/bin:/nix/store/h3i0acpmr8mrjx07519xxmidv8mpax4y-python3-3.12.5/bin:/nix/store/20543wg7279v4xskxi9kr3dkw93dllai-python3.12-poetry-1.8.3/bin:/nix/store/8rwmh4inpin8ljyc2n4r1ylrbd29iig5-python3.12-build-1.2.1/bin:/nix/store/gwn2a8a7mfh0vv7rpvcw1ksm40l4sz57-python3.12-cachecontrol-0.14.0/bin:/nix/store/mdjc15jlsywd76vzf0mkaxy7qdv6lk7h-python3.12-charset-normalizer-3.3.2/bin:/nix/store/8zmf2314d6r7w3wfgdzb9x1ahf8n8qr3-python3.12-dulwich-0.22.1/bin:/nix/store/j52ap4ryks5s2iicxpf62a7n81c8pabk-python3.12-keyring-25.3.0/bin:/nix/store/021f5qi4ma011hcsrpw1bdfsiwclb7x5-python3.12-pkginfo-1.11.1/bin:/nix/store/9x7i1h7h0d2zyldqvk4rw3q1nwnsbjfy-python3.12-virtualenv-20.26.2/bin:/home/tuto/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/home/tuto/.cargo/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
2024-10-16T12:18:18.966788788+02:00 [INFO] Initializing default prettier with plugins {}
2024-10-16T12:18:18.966869666+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:18.966901304+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:18.966952917+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:18.966980086+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:18.967007813+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:18.967035471+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:18.9670625+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:18.967118304+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:18.967145472+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:18.967172501+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:18.967200508+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:18.967228165+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:18.967255264+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:18.974327269+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-16T12:18:19.003185968+02:00 [INFO] Initializing default prettier with plugins {}
2024-10-16T12:18:19.003251759+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:19.003280394+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:19.003305607+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:19.00333082+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:19.003356383+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:19.003381596+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:19.003406878+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:19.003432161+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:19.003457514+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:19.003482797+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:19.00350794+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:19.003533223+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:19.003558087+02:00 [WARN] no language server found matching 'ruff'
2024-10-16T12:18:19.005568562+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-16T12:18:19.063235185+02:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-10-16T10:18:19.056Z] Agent service starting",
  "metadataStr": "[DEBUG] [agent] [2024-10-16T10:18:19.056Z]",
  "extra": [
    "Agent service starting"
  ]
}
2024-10-16T12:18:19.065892958+02:00 [INFO] Language server with id 0 sent unhandled notification client/registerCapability:
{
  "registrations": [
    {
      "id": "d6b3e6cd-0676-4d93-b380-51a92bb8317f",
      "method": "workspace/didChangeWorkspaceFolders",
      "registerOptions": {}
    }
  ]
}
2024-10-16T12:18:19.111307594+02:00 [ERROR] failed to fetch cached embeddings via cloud model

Caused by:
    RPC request GetCachedEmbeddings failed: permission denied
2024-10-16T12:18:19.162580519+02:00 [INFO] downloading language server "pyright"
2024-10-16T12:18:19.450547731+02:00 [INFO] using project environment for language server LanguageServerName("pyright")
2024-10-16T12:18:19.450824166+02:00 [INFO] starting language server process. binary path: "/home/tuto/.nix-profile/bin/node", working directory: "/home/tuto/git/greenbone/opensight-network", args: ["/home/tuto/.local/share/zed/languages/pyright/node_modules/pyright/langserver.index.js", "--stdio"]
2024-10-16T12:18:19.466279601+02:00 [INFO] Language server with id 0 sent unhandled notification LogMessage:
{
  "level": 0,
  "message": "[DEBUG] [agent] [2024-10-16T10:18:19.455Z] Telemetry initialized",
  "metadataStr": "[DEBUG] [agent] [2024-10-16T10:18:19.455Z]",
  "extra": [
    "Telemetry initialized"
  ]
}
2024-10-16T12:18:19.790665084+02:00 [INFO] language server 1: unregistered workspace/DidChangeWatchedFiles capability with id 2c9aed43-3a06-487e-aeea-db4419c4b185
2024-10-16T12:18:20.471450496+02:00 [INFO] Initializing default prettier with plugins {}
2024-10-16T12:18:20.471518593+02:00 [INFO] attempting to start language server "ruff", path: "/home/tuto/git/greenbone/opensight-network", id: 2
2024-10-16T12:18:20.482685511+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-16T12:18:20.48307558+02:00 [INFO] starting language server process. binary path: "/home/tuto/.cache/pypoetry/virtualenvs/opensight-network-ce-P5aor-py3.12/bin/ruff", working directory: "/home/tuto/git/greenbone/opensight-network", args: ["server"]
2024-10-16T12:18:20.49518837+02:00 [ERROR] cannot read LSP message headers
2024-10-16T12:18:20.495371496+02:00 [ERROR] Broken pipe (os error 32)
2024-10-16T12:18:20.49545391+02:00 [ERROR] server shut down
2024-10-16T12:18:20.495519003+02:00 [ERROR] Failed to start language server "ruff": oneshot canceled
2024-10-16T12:18:20.495557067+02:00 [ERROR] server stderr: "error: --preview needs to be provided as a command line argument while the server is still unstable.\nFor example: `ruff server --preview`\n"
2024-10-16T12:18:21.004479711+02:00 [INFO] open paths ["/home/tuto/.config/zed/settings.json"]
2024-10-16T12:18:21.027007709+02:00 [INFO] attempting to start language server "json-language-server", path: "/home/tuto/.config/zed/settings.json", id: 3
2024-10-16T12:18:21.027173305+02:00 [INFO] Initializing default prettier with plugins {}
2024-10-16T12:18:21.027589215+02:00 [INFO] Initializing default prettier with plugins {}
2024-10-16T12:18:21.027664575+02:00 [INFO] Initializing default prettier with plugins {}
2024-10-16T12:18:21.048647456+02:00 [INFO] fetching latest version of language server "json-language-server"
2024-10-16T12:18:21.049769749+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-16T12:18:21.600638879+02:00 [INFO] language server 1: unregistered workspace/DidChangeWatchedFiles capability with id 10e45456-b05b-4106-9158-c5d4d7f98950
2024-10-16T12:18:21.601307268+02:00 [INFO] language server 1: unregistered workspace/DidChangeWatchedFiles capability with id 2fc66d2e-dc17-436d-8462-5b61116a3974
2024-10-16T12:18:22.000170096+02:00 [INFO] downloading language server "json-language-server"
2024-10-16T12:18:22.349968967+02:00 [INFO] using project environment for language server LanguageServerName("json-language-server")
2024-10-16T12:18:22.3502373+02:00 [INFO] starting language server process. binary path: "/home/tuto/.nix-profile/bin/node", working directory: "/home/tuto/.config/zed", args: ["/home/tuto/.local/share/zed/languages/json-language-server/node_modules/vscode-langservers-extracted/bin/vscode-json-language-server", "--stdio"]
2024-10-16T12:18:24.484678297+02:00 [INFO] open paths ["/home/tuto/.config/zed/settings.json"]
2024-10-16T12:18:33.461422673+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-10-16T12:18:33.479236887+02:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-10-16T12:18:33.496099781+02:00 [INFO] Creating a descriptor pool for at most 256 sets
2024-10-16T12:18:33.512487818+02:00 [INFO] Creating a descriptor pool for at most 256 sets
2024-10-16T12:18:33.619589681+02:00 [INFO] Waiting for default prettier to install
2024-10-16T12:18:33.619676704+02:00 [INFO] Starting prettier at path "/home/tuto/.local/share/zed/prettier"
2024-10-16T12:18:33.737884513+02:00 [INFO] starting language server process. binary path: "/home/tuto/.nix-profile/bin/node", working directory: "/home/tuto/.local/share/zed/prettier", args: ["/home/tuto/.local/share/zed/prettier/prettier_server.js", "/home/tuto/.local/share/zed/prettier"]
2024-10-16T12:18:33.820770292+02:00 [INFO] Started default prettier in "/home/tuto/.local/share/zed/prettier"
2024-10-16T12:18:33.982029351+02:00 [INFO] stopping language server pyright
2024-10-16T12:18:33.982212826+02:00 [INFO] stopping language server ruff
2024-10-16T12:18:33.985204164+02:00 [WARN] request completed with error: failed to connect to the server
2024-10-16T12:18:33.992779591+02:00 [ERROR] oneshot canceled
2024-10-16T12:18:33.992983949+02:00 [INFO] attempting to start language server "pyright", path: "/home/tuto/git/greenbone/opensight-network", id: 5
2024-10-16T12:18:33.993056306+02:00 [INFO] attempting to start language server "ruff", path: "/home/tuto/git/greenbone/opensight-network", id: 6
2024-10-16T12:18:33.993288671+02:00 [INFO] starting language server process. binary path: "/home/tuto/.nix-profile/bin/ruff", working directory: "/home/tuto/git/greenbone/opensight-network", args: []
2024-10-16T12:18:34.005127611+02:00 [ERROR] cannot read LSP message headers
2024-10-16T12:18:34.005271765+02:00 [ERROR] Broken pipe (os error 32)
2024-10-16T12:18:34.00531828+02:00 [ERROR] server shut down
2024-10-16T12:18:34.005510834+02:00 [ERROR] Failed to start language server "ruff": oneshot canceled
2024-10-16T12:18:34.005539958+02:00 [ERROR] server stderr: "Ruff: An extremely fast Python linter and code formatter.\n\nUsage: ruff [OPTIONS] <COMMAND>\n"
2024-10-16T12:18:34.103086789+02:00 [INFO] using project environment for language server LanguageServerName("pyright")
2024-10-16T12:18:34.103281928+02:00 [INFO] starting language server process. binary path: "/home/tuto/.nix-profile/bin/node", working directory: "/home/tuto/git/greenbone/opensight-network", args: ["/home/tuto/.local/share/zed/languages/pyright/node_modules/pyright/langserver.index.js", "--stdio"]
2024-10-16T12:18:34.416456075+02:00 [INFO] language server 5: unregistered workspace/DidChangeWatchedFiles capability with id e6fd81f3-c4d7-4066-ba75-b71c77661496
2024-10-16T12:18:36.314285841+02:00 [ERROR] window not found
2024-10-16T12:18:36.314358197+02:00 [ERROR] window not found
2024-10-16T12:18:36.318620872+02:00 [ERROR] oneshot canceled
2024-10-16T12:18:36.31890946+02:00 [ERROR] oneshot canceled
2024-10-16T12:18:36.319028331+02:00 [ERROR] oneshot canceled
</pre></details>

**Comment by osiewicz** [comment]
Which build are you using? Zed Dev, Nightly, Preview or Stable?

**Comment by tuto193** [comment]
Stable `0.156.1`.
Also tried standalone binary for`0.156.2` (since it's not yet on Manjaro's `stable` branch) and had the same issues.

**Comment by tuto193** [comment]
Making an addendum to this issue:
While my initial tests/troubles were done on `0.156.1`, I have also tried the latest `stable` release (`0.157.5`), and still encountered the same issues.

In addition to this, I noticed a couple things:
1. `rust-analyzer` (the other LSP I currently use the most) also seems to _only_ work with the non-local version, and as soon as I specify a local binary it breaks with the same error as `pyright` and `ruff`.
2. In addition to this, *none* of my LSPs seem to work once there's no internet connection (internet off before starting `zed`). Even if I had already previously loaded my (non-local) LSPs, they still encountered the same error.

**Comment by cs2018ncsa** [comment]
@tuto193 are you by chance using poetry? i'm having the same issue when i launch set from a project using poetry but everything seems to be fine when running from outside of that project.

**Comment by tuto193** [comment]
> @tuto193 are you by chance using poetry? i'm having the same issue when i launch set from a project using poetry but everything seems to be fine when running from outside of that project.

Oh, indeed. Im indeed using poetry. I was also using poetry when it worked before.

Did it also work for you before?

**Comment by cs2018ncsa** [comment]
yep! i just tried upgrading ruff in my env and that didn't help. i also have pre-commit configured w/ the following config:

```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  -   repo: https://github.com/python-poetry/poetry
      rev: '1.8.0'  # add version here
      hooks:
      -   id: poetry-check
      -   id: poetry-lock
      -   id: poetry-export
      -   id: poetry-install
```

**Comment by tuto193** [comment]
> yep! i just tried upgrading ruff in my env and that didn't help but when i remove ruff from poetry env, it works fine.

Well, this did indeed solve my problem! I don't know if it's still a bug/defect though. I would have assumed that setting `ignore_system_version = true` would have prevented this.

**Comment by mrwunderbar666** [comment]
Not using poetry and have the same issue. Ruff / basedpyright worked perfectly fine (local and remote), but since the recent update 0.157.5 not working anymore. Now on Zed version 0.158.2 and issue persists. Using Ubuntu as OS

**Comment by msublee** [comment]
I have the same issue, too. Zed version `0.159.7`
It works well locally without any problem, but on remote, Ruff formatting does not work, and `[ERROR] oneshot canceled` is recorded in `Zed.log`.

**Comment by kjvdven** [comment]
I have the same error with rubocop 

```
Language server error: rubocop

oneshot canceled
-- stderr--
```

**Comment by choucavalier** [comment]
same here, ruff works locally but not on the remote!

**Comment by graf0** [comment]
same here, rubocop gives:

```
Language server error: rubocop

oneshot canceled
-- stderr--
```

**Comment by kjvdven** [comment]
Hello @osiewicz,

I didn't dismiss any popups.

I'm not sure but I suspect my Version Manager to maybe be part of this issue, that with switching ruby versions it goes wrong with PATH. I use Mise with Fish, btw.

**Comment by lordpengwin** [comment]
Same error for Java

`Language server error: jdtls

oneshot canceled
-- stderr--
WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
Jan 31, 2025 8:31:40 AM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider ch.qos.logback.classic.servlet.LogbackServletContainerInitializer of service jakarta.servlet.ServletContainerInitializer in bundle ch.qos.logback.classic
Jan 31, 2025 8:31:40 AM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider ch.qos.logback.classic.spi.LogbackServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle ch.qos.logback.classic
`

**Comment by Mathias206** [comment]
> Same error for Java
> 
> `Language server error: jdtls
> 
> oneshot canceled -- stderr-- WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign Jan 31, 2025 8:31:40 AM org.apache.aries.spifly.BaseActivator log INFO: Registered provider ch.qos.logback.classic.servlet.LogbackServletContainerInitializer of service jakarta.servlet.ServletContainerInitializer in bundle ch.qos.logback.classic Jan 31, 2025 8:31:40 AM org.apache.aries.spifly.BaseActivator log INFO: Registered provider ch.qos.logback.classic.spi.LogbackServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle ch.qos.logback.classic `

i also had the same error with java

**Comment by Mathias206** [comment]
You gys can try running the LSP directly from the terminal (I believe the error message will display the path to the LSP binary) and check what error it returns. Usually, a log file with more details about the issue will be generated.

**Comment by MrYakobo** [comment]
Just chiming in this issue. I had a very old version of `ruff` installed on my system, which made `ruff server` fail, due to no file being named "server" exists.

Try running `ruff server` in a terminal, and update your version if that doesn't work

**Comment by lordpengwin** [comment]
I see this in my log file
`!ENTRY org.eclipse.osgi 4 0 2025-02-17 08:31:41.220
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Application "org.eclipse.jdt.ls.core.id1" could not be found in the registry. The applications available are: org.eclipse.ant.core.antRunner, org.eclipse.equinox.app.error, org.eclipse.jdt.apt.core.aptBuild, org.eclipse.jdt.core.JavaIndexer.
        at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:264)
        at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:34)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1454)`

**Comment by Mathias206** [comment]
> I see this in my log file `!ENTRY org.eclipse.osgi 4 0 2025-02-17 08:31:41.220 !MESSAGE Application error !STACK 1 java.lang.RuntimeException: Application "org.eclipse.jdt.ls.core.id1" could not be found in the registry. The applications available are: org.eclipse.ant.core.antRunner, org.eclipse.equinox.app.error, org.eclipse.jdt.apt.core.aptBuild, org.eclipse.jdt.core.JavaIndexer. at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:264) at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:34) at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143) at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109) at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439) at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:569) at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668) at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605) at org.eclipse.equinox.launcher.Main.run(Main.java:1481) at org.eclipse.equinox.launcher.Main.main(Main.java:1454)`

JDTLS requires Java version 21 to run. Which version are you using?

**Comment by lordpengwin** [comment]
Ah, i'm using Java 17

**Comment by Blackbird314** [comment]
the same issue with Java extension(I installed openjdk23 and Zed by scoop):

```
Language server error: jdtls

oneshot canceled
-- stderr--
```

**Comment by lordpengwin** [comment]
Updating to Java 23 worked for me.

**Comment by Blackbird314** [comment]
> Updating to Java 23 worked for me.

Now it works…it's confusing that I did nothing except changing my Network settings. Maybe the jdtls needs to update.

**Comment by KornesWerkman** [comment]
Something similar here, using zed 0.177.8 on Mac

`Language server error: ruff

error while executing at wasm backtrace:
    0: 0x1373f - zed_ruff.wasm!rust_panic
    1: 0x13696 - zed_ruff.wasm!std::panicking::rust_panic_with_hook::h002a9d757cec9266
    2: 0x128df - zed_ruff.wasm!std::panicking::begin_panic_handler::{{closure}}::h5e11e16f0cbe0dd6
    3: 0x12850 - zed_ruff.wasm!std::sys::backtrace::__rust_end_short_backtrace::h34d7c06dcd4fe40d
    4: 0x12fec - zed_ruff.wasm!rust_begin_unwind
    5: 0x846e - zed_ruff.wasm!core::panicking::panic_fmt::h7e49d43cccf0228e
    6: 0x2fdb - zed_ruff.wasm!core::slice::index::slice_end_index_len_fail::hd4374c81ba7a2894
    7: 0x117d6 - zed_ruff.wasm!<std::sys::pal::wasi::fs::ReadDir as core::iter::traits::iterator::Iterator>::next::he4d4ac3f8ccdea64
    8: 0x14163 - zed_ruff.wasm!std::sys::pal::wasi::fs::remove_dir_all_recursive::hfeb30a9063e65819
    9: 0x13e5b - zed_ruff.wasm!std::sys::pal::wasi::fs::remove_dir_all::hd252435211c84e77
   10: 0x24fd0 - zed_ruff.wasm!<zed_ruff[3de5c4208a363a46]::RuffExtension as zed_extension_api[ddab9613c637baf]::Extension>::language_server_command
   11: 0x204ad - zed_ruff.wasm!language-server-command
   12: 0x2a59f - zed_ruff.wasm!language-server-command.command_export
-- stderr--
`

**Comment by Avik-creator** [comment]
```code
Language server error: jdtls

oneshot canceled
-- stderr--
WARNING: Using incubator modules: jdk.incubator.vector
Mar 19, 2025 10:32:22 AM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider ch.qos.logback.classic.servlet.LogbackServletContainerInitializer of service jakarta.servlet.ServletContainerInitializer in bundle ch.qos.logback.classic
Mar 19, 2025 10:32:22 AM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider ch.qos.logback.classic.spi.LogbackServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle ch.qos.logback.classic
```

I am facing this error currently for java. I have Java 23 installed.

<img width="516" alt="Image" src="https://github.com/user-attachments/assets/a240b318-26af-4fc1-a6f7-939179573beb" />

**Comment by Blackbird314** [comment]
Similar error for clangd in Windows...

After downloading clangd language server, Zed didn't unzip `clangd_20.1.0.zip` automatically. I have to unzip the file manually then add the following settings:

```
"clangd": {
      "binary": {
        "path": "C:/Users/Blackbird/AppData/Local/Zed/languages/clangd/clangd_20.1.0/bin/clangd.exe",
        "arguments": []
      }
}
```

**Comment by Manuel030** [comment]
Any update on this issue? It effectively blocks me from using Zed Editor
