### ISSUE TITLE
Cannot log in to copilot

### ISSUE THREAD

**Issue by luckasw** [zed-industries/zed#21865]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I complete the steps to use copilot. Everything seems successful but in the configure your assistant menu the option to login to copilot persists. When you press the login button a window pops up saying "Copilot Enabled". 

I have tried logging out and in again, using "copilot: reinstall" from command palette.

### Environment

Zed: v0.164.2 (Zed)
OS: Linux Wayland arch unknown
Memory: 30.5 GiB
Architecture: x86_64
GPU: NVIDIA GeForce RTX 2060 || NVIDIA || 565.77

### If applicable, add mockups / screenshots to help explain present your vision of the feature

[Screencast_20241211_183523.webm](https://github.com/user-attachments/assets/1f457ee4-525c-400c-a920-e5923ce7fa26)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```
2024-12-11T18:42:27.981257854+02:00 [INFO] new;
2024-12-11T18:42:27.981624716+02:00 [INFO] keep_updated;
2024-12-11T18:42:27.981671617+02:00 [INFO] new;
2024-12-11T18:42:46.896963901+02:00 [INFO] Language server with id 0 sent unhandled notification featureFlagsNotification:
{
  "rt": false,
  "sn": false,
  "chat": true,
  "ic": true,
  "ep": false,
  "pc": false,
  "x": true
}
2024-12-11T18:42:54.561412839+02:00 [ERROR] oneshot canceled
2024-12-11T18:42:56.175471997+02:00 [INFO] starting language server process. binary path: "/usr/bin/node", working directory: "/", args: ["/home/qwerty/.local/share/zed/copilot/copilot-v0.7.0/dist/language-server.js", "--stdio"]
2024-12-11T18:42:56.635882603+02:00 [INFO] Language server with id 0 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[lsp] GitHub Copilot Language Server 1.236.0 initialized"
}
2024-12-11T18:42:56.639666418+02:00 [INFO] Language server with id 0 sent unhandled notification workspace/configuration:
{
  "items": [
    {
      "section": "github.copilot"
    },
    {
      "section": "github-enterprise"
    },
    {
      "section": "http"
    },
    {
      "section": "telemetry"
    }
  ]
}
2024-12-11T18:42:56.697283099+02:00 [INFO] Language server with id 0 sent unhandled notification window/logMessage:
{
  "type": 2,
  "message": "[certificates] Failed to parse certificate # ACCVRAIZ1\n Error: error:0480006C:PEM routines::no start line\n    at new X509Certificate (node:internal/crypto/x509:119:21)\n    at /home/qwerty/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:79:36\n    at Array.filter (<anonymous>)\n    at Cle.removeExpiredCertificates (/home/qwerty/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:77:32)\n    at Cle.getAllRootCAs (/home/qwerty/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:68:38)\n    at Rge.createSecureContext (/home/qwerty/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificates.ts:46:23) {\n  library: 'PEM routines',\n  reason: 'no start line',\n  code: 'ERR_OSSL_PEM_NO_START_LINE'\n}"
}
2024-12-11T18:42:56.697500431+02:00 [INFO] Language server with id 0 sent unhandled notification window/logMessage:
{
  "type": 2,
  "message": "[certificates] Failed to parse certificate # ACCVRAIZ1\n Error: error:0480006C:PEM routines::no start line\n    at new X509Certificate (node:internal/crypto/x509:119:21)\n    at /home/qwerty/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:79:36\n    at Array.filter (<anonymous>)\n    at Cle.removeExpiredCertificates (/home/qwerty/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:77:32)\n    at Cle.getAllRootCAs (/home/qwerty/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:68:38)\n    at Rge.createSecureContext (/home/qwerty/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificates.ts:46:23) {\n  library: 'PEM routines',\n  reason: 'no start line',\n  code: 'ERR_OSSL_PEM_NO_START_LINE'\n}"
}
2024-12-11T18:42:56.697533244+02:00 [INFO] Language server with id 0 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[certificates] Removed 2 expired certificates"
}
2024-12-11T18:42:57.223612492+02:00 [INFO] Language server with id 0 sent unhandled notification featureFlagsNotification:
{
  "rt": false,
  "sn": false,
  "chat": true,
  "ic": true,
  "ep": false,
  "pc": false,
  "x": true
}
2024-12-11T18:42:57.223706004+02:00 [INFO] Language server with id 0 sent unhandled notification conversation/preconditionsNotification:
{
  "results": [
    {
      "type": "chat_enabled",
      "status": "ok"
    }
  ],
  "status": "ok"
}
2024-12-11T18:43:15.846066251+02:00 [INFO] new;
2024-12-11T18:43:15.84647855+02:00 [INFO] keep_updated;
2024-12-11T18:43:15.846537665+02:00 [INFO] new;
2024-12-11T18:43:16.880364104+02:00 [INFO] new;
2024-12-11T18:43:16.88077474+02:00 [INFO] keep_updated;
2024-12-11T18:43:16.880829156+02:00 [INFO] new;
2024-12-11T18:43:30.235397265+02:00 [INFO] new;
2024-12-11T18:43:30.235903797+02:00 [INFO] keep_updated;
2024-12-11T18:43:30.235978432+02:00 [INFO] new;
2024-12-11T18:43:43.604037094+02:00 [INFO] Language server with id 0 sent unhandled notification featureFlagsNotification:
{
  "rt": false,
  "sn": false,
  "chat": true,
  "ic": true,
  "ep": false,
  "pc": false,
  "x": true
}
2024-12-11T18:43:51.80436938+02:00 [ERROR] oneshot canceled
2024-12-11T18:43:53.299634462+02:00 [INFO] starting language server process. binary path: "/usr/bin/node", working directory: "/", args: ["/home/qwerty/.local/share/zed/copilot/copilot-v0.7.0/dist/language-server.js", "--stdio"]
2024-12-11T18:43:53.766738997+02:00 [INFO] Language server with id 0 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[lsp] GitHub Copilot Language Server 1.236.0 initialized"
}
2024-12-11T18:43:53.766795957+02:00 [INFO] Language server with id 0 sent unhandled notification workspace/configuration:
{
  "items": [
    {
      "section": "github.copilot"
    },
    {
      "section": "github-enterprise"
    },
    {
      "section": "http"
    },
    {
      "section": "telemetry"
    }
  ]
}
2024-12-11T18:43:53.829200495+02:00 [INFO] Language server with id 0 sent unhandled notification window/logMessage:
{
  "type": 2,
  "message": "[certificates] Failed to parse certificate # ACCVRAIZ1\n Error: error:0480006C:PEM routines::no start line\n    at new X509Certificate (node:internal/crypto/x509:119:21)\n    at /home/qwerty/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:79:36\n    at Array.filter (<anonymous>)\n    at Cle.removeExpiredCertificates (/home/qwerty/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:77:32)\n    at Cle.getAllRootCAs (/home/qwerty/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:68:38)\n    at Rge.createSecureContext (/home/qwerty/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificates.ts:46:23) {\n  library: 'PEM routines',\n  reason: 'no start line',\n  code: 'ERR_OSSL_PEM_NO_START_LINE'\n}"
}
2024-12-11T18:43:53.829386105+02:00 [INFO] Language server with id 0 sent unhandled notification window/logMessage:
{
  "type": 2,
  "message": "[certificates] Failed to parse certificate # ACCVRAIZ1\n Error: error:0480006C:PEM routines::no start line\n    at new X509Certificate (node:internal/crypto/x509:119:21)\n    at /home/qwerty/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:79:36\n    at Array.filter (<anonymous>)\n    at Cle.removeExpiredCertificates (/home/qwerty/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:77:32)\n    at Cle.getAllRootCAs (/home/qwerty/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:68:38)\n    at Rge.createSecureContext (/home/qwerty/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificates.ts:46:23) {\n  library: 'PEM routines',\n  reason: 'no start line',\n  code: 'ERR_OSSL_PEM_NO_START_LINE'\n}"
}
2024-12-11T18:43:53.829420181+02:00 [INFO] Language server with id 0 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[certificates] Removed 2 expired certificates"
}
2024-12-11T18:43:54.266844964+02:00 [INFO] Language server with id 0 sent unhandled notification featureFlagsNotification:
{
  "rt": false,
  "sn": false,
  "chat": true,
  "ic": true,
  "ep": false,
  "pc": false,
  "x": true
}
2024-12-11T18:43:54.266942564+02:00 [INFO] Language server with id 0 sent unhandled notification conversation/preconditionsNotification:
{
  "results": [
    {
      "type": "chat_enabled",
      "status": "ok"
    }
  ],
  "status": "ok"
}

```
</details>

**Comment by bennetbo** [comment]
See https://github.com/zed-industries/zed/issues/21750#issuecomment-2531551528. In fact the 0.165 is building while i type, so this will be fixed on stable in a few minutes
