### ISSUE TITLE
"Dock left" and "Dock right" buttons aren't working

### ISSUE THREAD

**Issue by marcospb19** [zed-industries/zed#22029]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

I'm on the latest commit at `main`.

When I right click on a panel icon at the bottom:

![image](https://github.com/user-attachments/assets/5ea38bf2-d9b7-45c7-ad7e-78b82d801ac6)

And click on "Dock right", nothing happens.

Same for "Dock left".

### Environment

Zed: v0.167.0 (Zed Dev 9daa426e936c5d0b2f3a24e1cffde434c38a13de)
OS: Linux X11 arch unknown
Memory: 31.2 GiB
Architecture: x86_64
GPU: AMD Radeon RX 6750 XT || AMD open-source driver || 2024.Q4.2 (LLPC)

### I see no related info in the logs

<details><summary>Zed.log</summary>

```
2024-12-14T21:19:46.747941543-03:00 [INFO] Ray tracing is supported
2024-12-14T21:19:46.75495175-03:00 [INFO] Using surface present mode MAILBOX
2024-12-14T21:19:46.755002406-03:00 [WARN] Unable to forbid exclusive full screen
2024-12-14T21:19:46.780494307-03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-12-14T21:19:46.780726613-03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-12-14T21:19:46.780760347-03:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-12-14T21:19:46.817888955-03:00 [INFO] Refreshing at 6251 micros
2024-12-14T21:19:46.817993492-03:00 [INFO] x11: no compositor present, falling back to server-side window decorations
2024-12-14T21:19:46.819383011-03:00 [INFO] Using GPU: GPUSpecs { is_software_emulated: false, device_name: "AMD Radeon RX 6750 XT", driver_name: "AMD open-source driver", driver_info: "2024.Q4.2 (LLPC)" }
2024-12-14T21:19:46.84103473-03:00 [INFO] Opening main db
2024-12-14T21:19:47.652852046-03:00 [INFO] starting language server process. binary path: "/usr/bin/node", working directory: "/", args: ["/home/marcospb19/.local/share/zed/copilot/copilot-v0.7.0/dist/language-server.js", "--stdio"]
2024-12-14T21:19:49.485946709-03:00 [INFO] Language server with id 0 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[lsp] GitHub Copilot Language Server 1.236.0 initialized"
}
2024-12-14T21:19:49.486814518-03:00 [INFO] Language server with id 0 sent unhandled notification workspace/configuration:
{
  "items": [
    {
      "section": "github.copilot"
    },
    {
      "section": "github-enterprise"
    },
    {
      "section": "http"
    },
    {
      "section": "telemetry"
    }
  ]
}
2024-12-14T21:19:49.673188009-03:00 [INFO] Language server with id 0 sent unhandled notification window/logMessage:
{
  "type": 2,
  "message": "[certificates] Failed to parse certificate # ACCVRAIZ1\n Error: error:0480006C:PEM routines::no start line\n    at new X509Certificate (node:internal/crypto/x509:119:21)\n    at /home/marcospb19/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:79:36\n    at Array.filter (<anonymous>)\n    at Cle.removeExpiredCertificates (/home/marcospb19/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:77:32)\n    at Cle.getAllRootCAs (/home/marcospb19/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:68:38)\n    at Rge.createSecureContext (/home/marcospb19/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificates.ts:46:23) {\n  library: 'PEM routines',\n  reason: 'no start line',\n  code: 'ERR_OSSL_PEM_NO_START_LINE'\n}"
}
2024-12-14T21:19:49.674546331-03:00 [INFO] Language server with id 0 sent unhandled notification window/logMessage:
{
  "type": 2,
  "message": "[certificates] Failed to parse certificate # ACCVRAIZ1\n Error: error:0480006C:PEM routines::no start line\n    at new X509Certificate (node:internal/crypto/x509:119:21)\n    at /home/marcospb19/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:79:36\n    at Array.filter (<anonymous>)\n    at Cle.removeExpiredCertificates (/home/marcospb19/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:77:32)\n    at Cle.getAllRootCAs (/home/marcospb19/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:68:38)\n    at Rge.createSecureContext (/home/marcospb19/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificates.ts:46:23) {\n  library: 'PEM routines',\n  reason: 'no start line',\n  code: 'ERR_OSSL_PEM_NO_START_LINE'\n}"
}
2024-12-14T21:19:49.675160174-03:00 [INFO] Language server with id 0 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[certificates] Removed 2 expired certificates"
}
2024-12-14T21:19:50.353837727-03:00 [INFO] Language server with id 0 sent unhandled notification featureFlagsNotification:
{
  "rt": false,
  "sn": false,
  "chat": true,
  "ic": true,
  "ep": false,
  "pc": false,
  "x": true
}
2024-12-14T21:19:50.353917788-03:00 [INFO] Language server with id 0 sent unhandled notification conversation/preconditionsNotification:
{
  "results": [
    {
      "type": "chat_enabled",
      "status": "ok"
    }
  ],
  "status": "ok"
}
2024-12-14T21:21:10.230902044-03:00 [INFO] Using surface present mode MAILBOX
2024-12-14T21:21:10.231002242-03:00 [WARN] Unable to forbid exclusive full screen

```
</details>

**Comment by marcospb19** [comment]
This is what my `settings.json` look like after clicking these buttons:


```json
{
  "collaboration_panel": {
    "dock": "right"
  },
  "project_panel": {
    "dock": "right"
  },
  "terminal": {
    "dock": "left"
  },
  "chat_panel": {
    "dock": "right"
  },
```

After I delete these from the settings, changing Dock Position works once, then, it updates `settings.json` and stops working again for subsequent clicks.

**Comment by marcospb19** [comment]
Ok, saw these on logs:

```
2024-12-14T21:38:54.186971061-03:00 [INFO] ignoring macOS specific set_edited
2024-12-14T21:38:54.286865098-03:00 [ERROR] ignoring event "/home/marcospb19/.config/zed/settings.json" outside of root path "/home/marcospb19/dotfiles/zed/.config/zed/settings.json"
2024-12-14T21:39:06.107130947-03:00 [ERROR] ignoring event "/home/marcospb19/.config/zed/settings.json" outside of root path "/home/marcospb19/dotfiles/zed/.config/zed/settings.json"
2024-12-14T21:40:49.86855796-03:00 [ERROR] ignoring event "/home/marcospb19/.config/zed/settings.json" outside of root path "/home/marcospb19/dotfiles/zed/.config/zed/settings.json"
```

My `settings.json` are linked from another file, but this used to work no problem :thinking:.

**Comment by notpeter** [comment]
I am not able to reproduce this (on macOS). The Dock Left / Dock Right actions (for me) work as expected: the panels move to the specified dock and my settings.json is updated accordingly.

Can you reproduce this with an empty settings file?

I have sometimes seen something similar when there is something broken in settings.json (invalid JSON, etc) which prevents Zed from fully apply settings changes / editing settings.json as normally succeeds.

**Comment by marcospb19** [comment]
@notpeter yes, I can reproduce starting from an empty settings and keymap file.

I tried going back to v0.160.x when it used to work, but it's still broken for me.

Are there folders where Zed stores any state? So I can make a backup, clear some files, see if it fixes it, reapply the files, see if it's broken again, etc.

**Comment by marcospb19** [comment]
I can't reproduce it anymore on Nightly, closing for now, if it happens again I'll reopen.
