### ISSUE TITLE
Zed is continually writing to disk while idling +1

### ISSUE THREAD

**Issue by WilgnerFSDev** [zed-industries/zed#22243]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Zed consistently writes to the disk at around 80 KiB/s on "zed-cli:///tmp/.tmprIEAsQ/socket", even when idle, regardless of the project or whether it is in the foreground or not.

### Zed Version and System Specs

Zed: v0.165.4 (Zed)
OS: Linux X11 manjaro unknown
Memory: 15.5 GiB
Architecture: x86_64
GPU: NVIDIA GeForce GTX 1650 || NVIDIA || 550.135

### If applicable, add screenshots or screencasts of the incorrect state / behavior

![image](https://github.com/user-attachments/assets/69983e15-ac16-4491-ae95-f0b38021fc30)

### If applicable, attach your Zed.log file to this issue.

<details><summary>Zed.log</summary>

```
2024-12-19T07:47:36.697454673-03:00 [INFO] ========== starting zed ==========
2024-12-19T07:47:36.770792586-03:00 [INFO] Compositor detection: _NET_WM_CM_S?=false, _NET_WM_CM_OWNER=false, _NET_SUPPORTING_WM_CHECK=true
2024-12-19T07:47:36.777651941-03:00 [INFO] x11: compositor present: true, gtk_frame_extents_supported: true
2024-12-19T07:47:36.805568733-03:00 [INFO] Try connect ibus
2024-12-19T07:47:36.806394445-03:00 [INFO] perform;
2024-12-19T07:47:36.806425358-03:00 [INFO] authenticate;
2024-12-19T07:47:36.80647412-03:00 [INFO] read_command;
2024-12-19T07:47:36.806512373-03:00 [INFO] send_secondary_commands;
2024-12-19T07:47:36.806840489-03:00 [INFO] new;
2024-12-19T07:47:36.80701187-03:00 [INFO] Opening main db
2024-12-19T07:47:36.807044816-03:00 [INFO] socket reader;
2024-12-19T07:47:36.807684904-03:00 [INFO] keep_updated;
2024-12-19T07:47:36.808639479-03:00 [INFO] Opening main db
2024-12-19T07:47:36.811456665-03:00 [INFO] Using git binary path: None
2024-12-19T07:47:36.856361689-03:00 [INFO] No prompt template overrides directory found at /home/myuser/.local/share/zed/prompt_overrides. Using built-in prompts.
2024-12-19T07:47:36.85713282-03:00 [INFO] extensions updated. loading 6, reloading 0, unloading 0
2024-12-19T07:47:36.859098925-03:00 [INFO] activate is not implemented on Linux, ignoring the call
2024-12-19T07:47:36.904344043-03:00 [INFO] set environment variables from shell:/bin/zsh, path:/home/myuser/.local/bin:/home/myuser/.config/composer/vendor/bin:/home/myuser/.go/bin:/home/myuser/.cargo/bin:./vendor/bin:/home/myuser/.local/share/bob/nvim-bin:/home/myuser/Code/jessarcher/dotfiles/scripts:tools/:platform-tools/:/usr/local/bin:/usr/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/rocm/bin:/home/myuser/.local/share/JetBrains/Toolbox/scripts
2024-12-19T07:47:36.907575769-03:00 [INFO] Opening main db
2024-12-19T07:47:36.908485897-03:00 [INFO] perform;
2024-12-19T07:47:36.908521129-03:00 [INFO] authenticate;
2024-12-19T07:47:36.908570966-03:00 [INFO] read_command;
2024-12-19T07:47:36.908934005-03:00 [INFO] socket reader;
2024-12-19T07:47:36.913818967-03:00 [INFO] Using Visual { id: 607, colormap: 0, depth: 32 }
2024-12-19T07:47:36.913845806-03:00 [INFO] Creating colormap 54525955
2024-12-19T07:47:36.915912609-03:00 [INFO] building git repository, `.git` path in the worktree: ".git"
2024-12-19T07:47:36.958183822-03:00 [INFO] Enabling Vulkan Portability
2024-12-19T07:47:36.958209415-03:00 [INFO] Enabling color space support
2024-12-19T07:47:36.972140902-03:00 [INFO] Adapter: "NVIDIA GeForce GTX 1650"
2024-12-19T07:47:36.977326821-03:00 [INFO] No ray tracing extensions are supported
2024-12-19T07:47:37.007076663-03:00 [INFO] Using surface present mode IMMEDIATE
2024-12-19T07:47:37.007219165-03:00 [WARN] Unable to forbid exclusive full screen
2024-12-19T07:47:37.031668257-03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-12-19T07:47:37.03170742-03:00 [INFO] Creating a descriptor pool for at most 16 sets
2024-12-19T07:47:37.031728224-03:00 [INFO] Initializing Blade pipelines for surface SurfaceInfo { format: Bgra8UnormSrgb, alpha: Ignored }
2024-12-19T07:47:37.133512164-03:00 [INFO] Refreshing at 4166 micros
2024-12-19T07:47:37.134830011-03:00 [INFO] Using GPU: GPUSpecs { is_software_emulated: false, device_name: "NVIDIA GeForce GTX 1650", driver_name: "NVIDIA", driver_info: "550.135" }
2024-12-19T07:47:37.175492858-03:00 [WARN] GPU frame is out of date
2024-12-19T07:47:37.17705077-03:00 [WARN] Acquire failed because the surface is out of date
2024-12-19T07:47:37.181615544-03:00 [INFO] Using surface present mode IMMEDIATE
2024-12-19T07:47:37.181769545-03:00 [WARN] Unable to forbid exclusive full screen
2024-12-19T07:47:37.20834247-03:00 [WARN] Acquire failed because the surface is out of date
2024-12-19T07:47:37.208462761-03:00 [INFO] XConnected server on 27262996, transport version: 0.0, TRANSPORT_MAX: 20
2024-12-19T07:47:37.215248567-03:00 [INFO] Using surface present mode IMMEDIATE
2024-12-19T07:47:37.215344178-03:00 [WARN] Unable to forbid exclusive full screen
2024-12-19T07:47:37.269824426-03:00 [INFO] Opening main db
2024-12-19T07:47:37.279940242-03:00 [INFO] open paths ["/home/myuser/.config/zed/keymap.json"]
2024-12-19T07:47:37.2800161-03:00 [INFO] open paths ["/home/myuser/.config/zed/settings.json"]
2024-12-19T07:47:37.292772992-03:00 [ERROR] missing field `name` at line 82 column 1
2024-12-19T07:47:37.292869106-03:00 [INFO] Opening main db
2024-12-19T07:47:37.515460836-03:00 [INFO] using project environment variables from CLI. PATH="/home/myuser/.local/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/rocm/bin:/home/myuser/.local/share/JetBrains/Toolbox/scripts"
2024-12-19T07:47:37.571903824-03:00 [INFO] attempting to start language server "json-language-server", path: "/home/myuser/.config/zed/keymap.json", id: 1
2024-12-19T07:47:37.571972619-03:00 [INFO] Initializing default prettier with plugins {}
2024-12-19T07:47:37.572269346-03:00 [INFO] attempting to start language server "json-language-server", path: "/home/myuser/.config/zed/settings.json", id: 2
2024-12-19T07:47:37.572308265-03:00 [INFO] Initializing default prettier with plugins {}
2024-12-19T07:47:37.572607825-03:00 [INFO] Initializing default prettier with plugins {}
2024-12-19T07:47:37.572634957-03:00 [INFO] Initializing default prettier with plugins {}
2024-12-19T07:47:37.5908734-03:00 [INFO] fetching latest version of language server "json-language-server"
2024-12-19T07:47:37.63612468-03:00 [INFO] Initializing default prettier with plugins {}
2024-12-19T07:47:37.636188751-03:00 [INFO] Initializing default prettier with plugins {}
2024-12-19T07:47:37.66757966-03:00 [INFO] Initializing default prettier with plugins {}
2024-12-19T07:47:37.667623559-03:00 [INFO] Initializing default prettier with plugins {}
2024-12-19T07:47:37.686050878-03:00 [INFO] ignoring macOS specific set_edited
2024-12-19T07:47:37.948861058-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:37.948912131-03:00 [INFO] attempting to start language server "tailwindcss-language-server", path: "/home/myuser/Documentos/CodeRockets/facil-vendas", id: 3
2024-12-19T07:47:37.949007232-03:00 [INFO] Initializing default prettier with plugins {"@prettier/plugin-php"}
2024-12-19T07:47:37.950266344-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:37.950313298-03:00 [INFO] Initializing default prettier with plugins {"@prettier/plugin-php"}
2024-12-19T07:47:37.951656191-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:37.95196792-03:00 [INFO] Initializing default prettier with plugins {"@prettier/plugin-php"}
2024-12-19T07:47:37.953250345-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:37.954138285-03:00 [INFO] Initializing default prettier with plugins {"@prettier/plugin-php"}
2024-12-19T07:47:37.955406872-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:37.955458532-03:00 [INFO] Initializing default prettier with plugins {"@prettier/plugin-php"}
2024-12-19T07:47:37.957013373-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:37.957059419-03:00 [INFO] Initializing default prettier with plugins {"@prettier/plugin-php"}
2024-12-19T07:47:37.957493923-03:00 [INFO] Initializing default prettier with plugins {"@prettier/plugin-php"}
2024-12-19T07:47:37.957527395-03:00 [INFO] Initializing default prettier with plugins {"@prettier/plugin-php"}
2024-12-19T07:47:37.957553657-03:00 [INFO] Initializing default prettier with plugins {"@prettier/plugin-php"}
2024-12-19T07:47:37.957591533-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:37.957624104-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:37.957653661-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:37.957689663-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:37.95771941-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:37.95776326-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:37.973091802-03:00 [INFO] fetching latest version of language server "tailwindcss-language-server"
2024-12-19T07:47:38.037364112-03:00 [INFO] Initializing default prettier with plugins {"@prettier/plugin-php"}
2024-12-19T07:47:38.037550339-03:00 [INFO] Initializing default prettier with plugins {"@prettier/plugin-php"}
2024-12-19T07:47:38.037580087-03:00 [INFO] Initializing default prettier with plugins {"@prettier/plugin-php"}
2024-12-19T07:47:38.037695109-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:38.037729601-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:38.037759461-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:38.037795638-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:38.037840964-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:38.037869817-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:38.194003307-03:00 [INFO] Initializing default prettier with plugins {"@prettier/plugin-php"}
2024-12-19T07:47:38.194062936-03:00 [INFO] Initializing default prettier with plugins {"@prettier/plugin-php"}
2024-12-19T07:47:38.194092225-03:00 [INFO] Initializing default prettier with plugins {"@prettier/plugin-php"}
2024-12-19T07:47:38.194126785-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:38.194157541-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:38.194183966-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:38.194214741-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:38.194239447-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:38.194265685-03:00 [WARN] no language server found matching 'intelephense'
2024-12-19T07:47:38.362248899-03:00 [INFO] Initializing default prettier with plugins {"@prettier/plugin-php"}
2024-12-19T07:47:38.362326217-03:00 [INFO] Initializing default prettier with plugins {"@prettier/plugin-php"}
2024-12-19T07:47:38.362360977-03:00 [INFO] Initializing default prettier with plugins {"@prettier/plugin-php"}
2024-12-19T07:47:38.362405355-03:00 [INFO] attempting to start language server "intelephense", path: "/home/myuser/Documentos/CodeRockets/facil-vendas", id: 4
2024-12-19T07:47:42.367874573-03:00 [INFO] starting language server process. binary path: "/usr/bin/node", working directory: "/", args: ["/home/myuser/.local/share/zed/copilot/copilot-v0.7.0/dist/language-server.js", "--stdio"]
2024-12-19T07:47:43.259162556-03:00 [INFO] Language server with id 0 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[lsp] GitHub Copilot Language Server 1.236.0 initialized"
}
2024-12-19T07:47:43.259267493-03:00 [INFO] Language server with id 0 sent unhandled notification workspace/configuration:
{
  "items": [
    {
      "section": "github.copilot"
    },
    {
      "section": "github-enterprise"
    },
    {
      "section": "http"
    },
    {
      "section": "telemetry"
    }
  ]
}
2024-12-19T07:47:43.397008083-03:00 [INFO] Language server with id 0 sent unhandled notification window/logMessage:
{
  "type": 2,
  "message": "[certificates] Failed to parse certificate # ACCVRAIZ1\n Error: error:0480006C:PEM routines::no start line\n    at new X509Certificate (node:internal/crypto/x509:119:21)\n    at /home/myuser/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:79:36\n    at Array.filter (<anonymous>)\n    at Cle.removeExpiredCertificates (/home/myuser/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:77:32)\n    at Cle.getAllRootCAs (/home/myuser/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:68:38)\n    at Rge.createSecureContext (/home/myuser/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificates.ts:46:23) {\n  library: 'PEM routines',\n  reason: 'no start line',\n  code: 'ERR_OSSL_PEM_NO_START_LINE'\n}"
}
2024-12-19T07:47:43.397321809-03:00 [INFO] Language server with id 0 sent unhandled notification window/logMessage:
{
  "type": 2,
  "message": "[certificates] Failed to parse certificate # ACCVRAIZ1\n Error: error:0480006C:PEM routines::no start line\n    at new X509Certificate (node:internal/crypto/x509:119:21)\n    at /home/myuser/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:79:36\n    at Array.filter (<anonymous>)\n    at Cle.removeExpiredCertificates (/home/myuser/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:77:32)\n    at Cle.getAllRootCAs (/home/myuser/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificateReaders.ts:68:38)\n    at Rge.createSecureContext (/home/myuser/.local/share/zed/copilot/copilot-v0.7.0/lib/src/network/certificates.ts:46:23) {\n  library: 'PEM routines',\n  reason: 'no start line',\n  code: 'ERR_OSSL_PEM_NO_START_LINE'\n}"
}
2024-12-19T07:47:43.397349684-03:00 [INFO] Language server with id 0 sent unhandled notification window/logMessage:
{
  "type": 3,
  "message": "[certificates] Removed 2 expired certificates"
}
2024-12-19T07:47:43.908008782-03:00 [INFO] downloading language server "tailwindcss-language-server"
2024-12-19T07:47:43.985543584-03:00 [INFO] downloading language server "json-language-server"
2024-12-19T07:47:44.262698109-03:00 [INFO] Installing default prettier and plugins: [("@prettier/plugin-php", "0.22.2"), ("prettier", "3.4.2")]
2024-12-19T07:47:44.301364096-03:00 [INFO] starting language server process. binary path: "/usr/bin/node", working directory: "/home/myuser/Documentos/CodeRockets/facil-vendas", args: ["/home/myuser/.local/share/zed/languages/tailwindcss-language-server/node_modules/.bin/tailwindcss-language-server", "--stdio"]
2024-12-19T07:47:44.413929924-03:00 [INFO] starting language server process. binary path: "/usr/bin/node", working directory: "/home/myuser/Documentos/CodeRockets/facil-vendas", args: ["/home/myuser/.local/share/zed/extensions/work/php/node_modules/intelephense/lib/intelephense.js", "--stdio"]
2024-12-19T07:47:44.5104194-03:00 [INFO] starting language server process. binary path: "/usr/bin/node", working directory: "/home/myuser/.config/zed", args: ["/home/myuser/.local/share/zed/languages/json-language-server/node_modules/vscode-langservers-extracted/bin/vscode-json-language-server", "--stdio"]
2024-12-19T07:47:44.51076581-03:00 [INFO] starting language server process. binary path: "/usr/bin/node", working directory: "/home/myuser/.config/zed", args: ["/home/myuser/.local/share/zed/languages/json-language-server/node_modules/vscode-langservers-extracted/bin/vscode-json-language-server", "--stdio"]
2024-12-19T07:47:47.270453539-03:00 [WARN] unhandled capability registration: Registration { id: "856f6458-8d8c-4cad-ad97-c7d64f78968a", method: "workspace/didChangeConfiguration", register_options: Some(Object {"section": String("intelephense")}) }
2024-12-19T07:47:47.63853542-03:00 [INFO] Language server with id 3 sent unhandled notification @/tailwindCSS/projectInitialized:
[
  null
]
2024-12-19T07:47:47.638691124-03:00 [WARN] unhandled capability registration: Registration { id: "6b078596-371c-4085-9113-79fe49d964bf", method: "workspace/didChangeWorkspaceFolders", register_options: Some(Object {}) }
2024-12-19T07:47:48.415725265-03:00 [INFO] Language server with id 4 sent unhandled notification indexingStarted:
[
  null
]
2024-12-19T07:47:49.268802824-03:00 [INFO] Language server with id 0 sent unhandled notification featureFlagsNotification:
{
  "rt": false,
  "sn": false,
  "chat": true,
  "ic": true,
  "ep": false,
  "pc": false,
  "x": true
}
2024-12-19T07:47:49.268866904-03:00 [INFO] Language server with id 0 sent unhandled notification conversation/preconditionsNotification:
{
  "results": [
    {
      "type": "chat_enabled",
      "status": "ok"
    }
  ],
  "status": "ok"
}
2024-12-19T07:47:50.420488517-03:00 [INFO] Initialized prettier with plugins: {"@prettier/plugin-php"}
2024-12-19T07:48:18.013945925-03:00 [INFO] Language server with id 4 sent unhandled notification indexingEnded:
[
  null
]
2024-12-19T07:48:46.606408473-03:00 [ERROR] oneshot canceled
2024-12-19T07:48:46.606486893-03:00 [ERROR] window not found
2024-12-19T07:48:46.606529949-03:00 [ERROR] window not found
2024-12-19T07:48:46.633457019-03:00 [ERROR] oneshot canceled
2024-12-19T07:48:46.633852167-03:00 [ERROR] oneshot canceled
2024-12-19T07:48:46.633934154-03:00 [ERROR] oneshot canceled
```
</details>

**Comment by SomeoneToIgnore** [comment]
https://github.com/zed-industries/zed/issues/16472
