### ISSUE TITLE
Panic: `attempt to subtract with overflow`

### ISSUE THREAD

**Issue by JosephTLyons** [zed-industries/zed#5081]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

-

### Environment

Zed 0.67.1 – /Applications/Zed Preview.app
macOS 13.0.1
architecture arm64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue

```shell
thread 'main' panicked at 'attempt to subtract with overflow': crates/project_symbols/src/project_symbols.rs:101   0: backtrace::backtrace::libunwind::trace
             at /Users/josephlyons/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/libunwind.rs:93:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/josephlyons/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:66:5
   1: backtrace::backtrace::trace
             at /Users/josephlyons/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/backtrace/mod.rs:53:14
   2: backtrace::capture::Backtrace::create
             at /Users/josephlyons/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:176:9
   3: backtrace::capture::Backtrace::new
             at /Users/josephlyons/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.66/src/capture.rs:140:22
   4: Zed::init_panic_hook::{{closure}}
             at crates/zed/src/main.rs:297:25
   5: std::panicking::rust_panic_with_hook
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:702:17
   6: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:586:13
   7: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
   8: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   9: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
  10: core::panicking::panic
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
  11: project_symbols::ProjectSymbolsView::filter
             at crates/project_symbols/src/project_symbols.rs:101:13
  12: <project_symbols::ProjectSymbolsView as picker::PickerDelegate>::update_matches
             at crates/project_symbols/src/project_symbols.rs:197:9
  13: picker::Picker<D>::update_matches::{{closure}}
             at crates/picker/src/picker.rs:229:54
  14: gpui::app::ViewHandle<T>::update::{{closure}}
             at crates/gpui/src/app.rs:4574:13
  15: <gpui::app::MutableAppContext as gpui::app::UpdateView>::update_view::{{closure}}
             at crates/gpui/src/app.rs:2664:26
  16: gpui::app::MutableAppContext::update
             at crates/gpui/src/app.rs:964:22
  17: <gpui::app::MutableAppContext as gpui::app::UpdateView>::update_view
             at crates/gpui/src/app.rs:2656:9
  18: <gpui::app::ViewContext<V> as gpui::app::UpdateView>::update_view
             at crates/gpui/src/app.rs:4272:9
  19: gpui::app::ViewHandle<T>::update
             at crates/gpui/src/app.rs:4572:9
  20: picker::Picker<D>::update_matches
             at crates/picker/src/picker.rs:229:26
  21: picker::Picker<D>::on_query_editor_event
             at crates/picker/src/picker.rs:215:51
  22: core::ops::function::FnMut::call_mut
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:164:5
  23: gpui::app::ViewContext<T>::subscribe::{{closure}}::{{closure}}
             at crates/gpui/src/app.rs:3811:25
  24: gpui::app::ViewHandle<T>::update::{{closure}}
             at crates/gpui/src/app.rs:4574:13
  25: <gpui::app::MutableAppContext as gpui::app::UpdateView>::update_view::{{closure}}
             at crates/gpui/src/app.rs:2664:26
  26: gpui::app::MutableAppContext::update
             at crates/gpui/src/app.rs:964:22
  27: <gpui::app::MutableAppContext as gpui::app::UpdateView>::update_view
             at crates/gpui/src/app.rs:2656:9
  28: gpui::app::ViewHandle<T>::update
             at crates/gpui/src/app.rs:4572:9
  29: gpui::app::ViewContext<T>::subscribe::{{closure}}
             at crates/gpui/src/app.rs:3810:21
  30: gpui::app::MutableAppContext::subscribe_internal::{{closure}}
             at crates/gpui/src/app.rs:1086:21
  31: <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1947:9
  32: gpui::app::MutableAppContext::flush_effects::{{closure}}
             at crates/gpui/src/app.rs:2011:33
  33: gpui::app::callback_collection::CallbackCollection<K,F>::emit_and_cleanup
             at crates/gpui/src/app/callback_collection.rs:85:33
  34: gpui::app::MutableAppContext::flush_effects
             at crates/gpui/src/app.rs:2010:29
  35: gpui::app::MutableAppContext::update
             at crates/gpui/src/app.rs:965:9
  36: gpui::app::App::update
             at crates/gpui/src/app.rs:344:22
  37: gpui::app::MutableAppContext::register_platform_window::{{closure}}
             at crates/gpui/src/app.rs:1764:17
  38: <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1947:9
  39: gpui::platform::mac::window::handle_key_event
             at crates/gpui/src/platform/mac/window.rs:930:31
  40: gpui::platform::mac::window::handle_key_down
             at crates/gpui/src/platform/mac/window.rs:871:5
  41: <unknown>
  42: <unknown>
  43: <(A,) as objc::message::MessageArguments>::invoke
             at /Users/josephlyons/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128:17
  44: objc::message::platform::send_super_unverified
             at /Users/josephlyons/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:38:9
  45: objc::message::send_super_message
             at /Users/josephlyons/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:205:5
      gpui::platform::mac::window::send_event
             at crates/gpui/src/platform/mac/window.rs:1051:21
  46: <unknown>
  47: <(A,) as objc::message::MessageArguments>::invoke
             at /Users/josephlyons/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128:17
  48: objc::message::platform::send_super_unverified
             at /Users/josephlyons/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:38:9
  49: objc::message::send_super_message
             at /Users/josephlyons/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:205:5
      gpui::platform::mac::platform::send_event
             at crates/gpui/src/platform/mac/platform.rs:812:9
  50: <unknown>
  51: <unknown>
  52: <() as objc::message::MessageArguments>::invoke
             at /Users/josephlyons/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:128:17
  53: objc::message::platform::send_unverified
             at /Users/josephlyons/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/apple/mod.rs:27:9
  54: objc::message::send_message
             at /Users/josephlyons/.cargo/registry/src/github.com-1ecc6299db9ec823/objc-0.2.7/src/message/mod.rs:178:5
      <*mut objc::runtime::Object as cocoa::appkit::NSApplication>::run
             at /Users/josephlyons/.cargo/git/checkouts/core-foundation-rs-0be28639533e3a9f/0796658/cocoa/src/appkit.rs:456:9
  55: <gpui::platform::mac::platform::MacForegroundPlatform as gpui::platform::ForegroundPlatform>::run
             at crates/gpui/src/platform/mac/platform.rs:300:13
  56: gpui::app::App::run
             at crates/gpui/src/app.rs:326:9
  57: Zed::main
             at crates/zed/src/main.rs:85:5
  58: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
  59: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:122:18
  60: std::rt::lang_start::{{closure}}
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:166:18
  61: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:283:13
      std::panicking::try::do_call
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:148:20
  62: std::rt::lang_start
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:165:17
  63: _main
```

**Comment by maxdeviant** [comment]
Closing this out since it's for an old version of Zed.

We can reopen if this panic resurfaces.
