### ISSUE TITLE
format_on_save option erase a whole file after triggered.

### ISSUE THREAD

**Issue by yceffort** [zed-industries/zed#6052]
### Check for existing issues

- [X] Completed

### settings 

```json
{
    "buffer_font_size": 15,
    "autosave": "on_focus_change",
    "format_on_save": "on",
    "language_overrides": {
        "TypeScript": {
            "format_on_save": {
                "external": {
                    "command": "node_modules/.bin/eslint",
                    "arguments": [
                        "--stdin-filename",
                        "{buffer_path}",
                        "--fix"
                    ]
                }
            }
        }
    }
}
```

Hello, I'm a new user using zed. There is a bug that deletes the entire file if I use the `format_on_save` option. This bug seems to be a problem with the ts-server.

### Environment

Zed: v0.77.3 (stable)
OS: macOS 13.2.1
Memory: 32 GiB
Architecture: aarch64

### If applicable, add mockups / screenshots to help explain present your vision of the feature

![1](https://user-images.githubusercontent.com/39641309/226634214-0e6e6616-5b1f-4fe0-a2a8-7068290678b2.gif)

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

```
BADCLIENT: Bad error code, 6133 not found in range 0..0 (found: ); could have caused this error:
Debug Failure. False expression: should not delete whole source file
Error: BADCLIENT: Bad error code, 6133 not found in range 0..0 (found: ); could have caused this error:
Debug Failure. False expression: should not delete whole source file
    at tryDeleteDeclarationWorker (/Users/yceffort/Library/Application Support/Zed/languages/typescript-language-server/typescript-5.0.2:server-3.3.0/node_modules/typescript/lib/tsserver.js:145129:11)
    at tryDeleteDeclaration (/Users/yceffort/Library/Application Support/Zed/languages/typescript-language-server/typescript-5.0.2:server-3.3.0/node_modules/typescript/lib/tsserver.js:145112:3)
    at /Users/yceffort/Library/Application Support/Zed/languages/typescript-language-server/typescript-5.0.2:server-3.3.0/node_modules/typescript/lib/tsserver.js:144959:82
    at Function.with (/Users/yceffort/Library/Application Support/Zed/languages/typescript-language-server/typescript-5.0.2:server-3.3.0/node_modules/typescript/lib/tsserver.js:163891:5)
    at Object.getCodeActions (/Users/yceffort/Library/Application Support/Zed/languages/typescript-language-server/typescript-5.0.2:server-3.3.0/node_modules/typescript/lib/tsserver.js:144959:65)
    at /Users/yceffort/Library/Application Support/Zed/languages/typescript-language-server/typescript-5.0.2:server-3.3.0/node_modules/typescript/lib/tsserver.js:138726:46
    at flatMap (/Users/yceffort/Library/Application Support/Zed/languages/typescript-language-server/typescript-5.0.2:server-3.3.0/node_modules/typescript/lib/tsserver.js:2555:17)
    at Object.getFixes (/Users/yceffort/Library/Application Support/Zed/languages/typescript-language-server/typescript-5.0.2:server-3.3.0/node_modules/typescript/lib/tsserver.js:138726:10)
    at /Users/yceffort/Library/Application Support/Zed/languages/typescript-language-server/typescript-5.0.2:server-3.3.0/node_modules/typescript/lib/tsserver.js:135894:33
    at flatMap (/Users/yceffort/Library/Application Support/Zed/languages/typescript-language-server/typescript-5.0.2:server-3.3.0/node_modules/typescript/lib/tsserver.js:2555:17)
    at Object.getCodeFixesAtPosition (/Users/yceffort/Library/Application Support/Zed/languages/typescript-language-server/typescript-5.0.2:server-3.3.0/node_modules/typescript/lib/tsserver.js:135892:12)
    at IpcIOSession.getCodeFixes (/Users/yceffort/Library/Application Support/Zed/languages/typescript-language-server/typescript-5.0.2:server-3.3.0/node_modules/typescript/lib/tsserver.js:179660:50)
    at getCodeFixes (/Users/yceffort/Library/Application Support/Zed/languages/typescript-language-server/typescript-5.0.2:server-3.3.0/node_modules/typescript/lib/tsserver.js:177805:43)
    at /Users/yceffort/Library/Application Support/Zed/languages/typescript-language-server/typescript-5.0.2:server-3.3.0/node_modules/typescript/lib/tsserver.js:179962:69
    at IpcIOSession.executeWithRequestId (/Users/yceffort/Library/Application Support/Zed/languages/typescript-language-server/typescript-5.0.2:server-3.3.0/node_modules/typescript/lib/tsserver.js:179954:14)
    at IpcIOSession.executeCommand (/Users/yceffort/Library/Application Support/Zed/languages/typescript-language-server/typescript-5.0.2:server-3.3.0/node_modules/typescript/lib/tsserver.js:179962:29)
    at IpcIOSession.onMessage (/Users/yceffort/Library/Application Support/Zed/languages/typescript-language-server/typescript-5.0.2:server-3.3.0/node_modules/typescript/lib/tsserver.js:180004:51)
    at process.<anonymous> (/Users/yceffort/Library/Application Support/Zed/languages/typescript-language-server/typescript-5.0.2:server-3.3.0/node_modules/typescript/lib/tsserver.js:181571:14)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
```

**Comment by smileart** [comment]
Using this `format_on_save` and having no standardjs installed yet, I get my code simply removed on save. Wouldn't it be better not to lose the entire file being saved if the external tool is not available and/or returns an empty STDOUT? Seems really inconvenient cause I can't even quit without loosing the code, only copying it elsewhere would save it. 😵

```json
  "language_overrides": {
    "JavaScript": {
      "format_on_save": {
        "external": {
          "command": "standard",
          "arguments": ["--fix"]
        }
      }
    },
    "JSX": {
      "format_on_save": {
        "external": {
          "command": "standard",
          "arguments": ["--fix"]
        }
      }
    }
  }
```
