### ISSUE TITLE
erb formatter fails with 'invalid byte sequence in US-ASCII'

### ISSUE THREAD

**Issue by sweetppro** [zed-industries/zed#8101]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Using the [erb-formatter](https://github.com/nebulab/erb-formatter) custom external formatter on .erb files fails with the error:
`failed to format via external command "erb-format"`

erb-formatter was installed like so:
`gem install erb-formatter`

and here are my settings:
```
"language_overrides": {
  "ERB": {
      "formatter": {
        "external": {
          "command": "erb-format",
          "arguments": [
            "{buffer_path}",
            "--write"
          ]
        }
      }
    }
}
```

### Environment

Zed: v0.122.2 (Zed)
OS: macOS 14.3.1
Memory: 24 GiB
Architecture: aarch64

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
If you only need the most recent lines, you can run the `zed: open log` command palette action to see the last 1000.

```
2024-02-21T06:08:52+01:00 [ERROR] crates/editor/src/editor.rs:7819: failed to format via external command "erb-format"

Caused by:
    command failed with exit code Some(1):
    stdout: 
    stderr: /Users/.../.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/erb-formatter-0.7.1/lib/erb/formatter.rb:98:in `gsub!': invalid byte sequence in US-ASCII (ArgumentError)
    
        @source.gsub!(ERB_PLACEHOLDER) { |tag| build_uid[].tap { |uid| pre_placeholders[uid] = tag } }
                      ^^^^^^^^^^^^^^^
    	from /Users/.../.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/erb-formatter-0.7.1/lib/erb/formatter.rb:98:in `initialize'
    	from /Users/.../.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/erb-formatter-0.7.1/lib/erb/formatter/command_line.rb:101:in `new'
    	from /Users/.../.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/erb-formatter-0.7.1/lib/erb/formatter/command_line.rb:101:in `block in run'
    	from /Users/.../.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/erb-formatter-0.7.1/lib/erb/formatter/command_line.rb:97:in `each'
    	from /Users/.../.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/erb-formatter-0.7.1/lib/erb/formatter/command_line.rb:97:in `run'
    	from /Users/.../.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/erb-formatter-0.7.1/exe/erb-format:5:in `<top (required)>'
    	from /Users/.../.rbenv/versions/3.3.0/bin/erb-format:25:in `load'
    	from /Users/.../.rbenv/versions/3.3.0/bin/erb-format:25:in `<main>'
```

**Comment by sweetppro** [comment]
I found a solution here:
https://github.com/rubygems/bundler/issues/1570#issuecomment-561194143

**Comment by sweetppro** [comment]
@luizkowalski im using these settings with htmlbeautify, and it works well:

```
"ERB": {
      "formatter": {
        "external": {
          "command": "htmlbeautifier",
          "arguments": []
        }
      }
    }
```

**Comment by JosephTLyons** [comment]
Is there anything left for us to do here @sweetppro? Maybe we should convert this into a Discussion with an accepted answer so others can see it?

**Comment by sweetppro** [comment]
@JosephTLyons 👍
