### ISSUE TITLE
Cannot open Zed

### ISSUE THREAD

**Issue by OSokunbi** [zed-industries/zed#9711]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

Cannot open Zed at all. I have tried to run this command: 

```
> RUST_BACKTRACE=full ./zed
thread 'main' panicked at crates/zed/src/main.rs:472:54:
could not create tmp path: Os { code: 20, kind: NotADirectory, message: "Not a directory" }
stack backtrace:
   0:        0x1060a6aec - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb478ebbfb46e27ce
   1:        0x10489c4c8 - core::fmt::write::he4d5fa2daff1f531
   2:        0x1060a205c - std::io::Write::write_fmt::hc5a47a68eba63d9f
   3:        0x1060a68e4 - std::sys_common::backtrace::print::h79bd952cc5812e7a
   4:        0x1060a8254 - std::panicking::default_hook::{{closure}}::h82301f6222887737
   5:        0x1060a7f50 - std::panicking::default_hook::h1e49abbb3f1d7dbf
   6:        0x1060a8858 - std::panicking::rust_panic_with_hook::h1e70c5d905e30e9d
   7:        0x1060a8634 - std::panicking::begin_panic_handler::{{closure}}::h399e32952efd26a4
   8:        0x1060a6f84 - std::sys_common::backtrace::__rust_end_short_backtrace::h2ab87f841a2323e7
   9:        0x1060a83c8 - _rust_begin_unwind
  10:        0x1078770f4 - core::panicking::panic_fmt::h33e40d2a93cab78f
  11:        0x1078774a8 - core::result::unwrap_failed::h79c2cb9e4fc28c72
  12:        0x1040ee8ec - Zed[5b2c4ff9e7167a66]::main
  13:        0x1040941a4 - std[fcd23fca98dce159]::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()>
  14:        0x1040bca20 - std[fcd23fca98dce159]::rt::lang_start::<()>::{closure#0}
  15:        0x106099cd8 - std::rt::lang_start_internal::hf4f3eb1e51305b96
  16:        0x104103ed8 - _main
```

```
$ sudo ./zed
thread 'main' panicked at crates/zed/src/main.rs:472:54:
could not create tmp path: Os { code: 20, kind: NotADirectory, message: "Not a directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Nothing is working. I also tried to reinstall it several times.

### Environment

MacOS Macbook Air Apple M2 

### If applicable, attach your `~/Library/Logs/Zed/Zed.log` file to this issue.
```
Caused by:
    0: WebSocket protocol error: Connection reset without closing handshake
    1: Connection reset without closing handshake
2024-03-21T14:29:34-04:00 [INFO] set status on client 112342: ConnectionLost
2024-03-21T14:29:34-04:00 [INFO] set status on client 112342: Reauthenticating
2024-03-21T14:29:34-04:00 [INFO] set status on client 112342: Reconnecting
2024-03-21T14:29:34-04:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-03-21T14:29:35-04:00 [INFO] add connection to peer
2024-03-21T14:29:35-04:00 [INFO] waiting for server hello
2024-03-21T14:29:35-04:00 [INFO] got server hello
2024-03-21T14:29:35-04:00 [INFO] set status to connected (connection id: ConnectionId { owner_id: 0, id: 329 }, peer id: PeerId { owner_id: 375, id: 293521 })
2024-03-21T14:29:35-04:00 [INFO] set status on client 112342: Connected { peer_id: PeerId { owner_id: 375, id: 293521 }, connection_id: ConnectionId { owner_id: 0, id: 329 } }
2024-03-21T14:44:16-04:00 [ERROR] connection error: error reading rpc message from socket
```
```
Caused by:
    0: WebSocket protocol error: Connection reset without closing handshake
    1: Connection reset without closing handshake
2024-03-21T14:44:16-04:00 [INFO] set status on client 112342: ConnectionLost
2024-03-21T14:44:16-04:00 [INFO] set status on client 112342: Reauthenticating
2024-03-21T14:44:16-04:00 [INFO] set status on client 112342: Reconnecting
2024-03-21T14:44:16-04:00 [INFO] connected to rpc endpoint https://collab.zed.dev/rpc
2024-03-21T14:44:17-04:00 [INFO] set status on client 112342: UpgradeRequired
2024-03-21T14:44:17-04:00 [ERROR] failed to connect upgrade required
2024-03-21T16:08:40-04:00 [ERROR] crates/ai/src/providers/open_ai/embedding.rs:177: NotPresent
2024-03-21T16:08:40-04:00 [ERROR] crates/semantic_index/src/semantic_index.rs:87: user is not authenticated
2024-03-21T16:08:43-04:00 [ERROR] crates/workspace/src/workspace.rs:4115: window not found
2024-03-21T16:08:43-04:00 [INFO] starting language server "clangd", path: "/Users/oni/Downloads/p4-editor/", id: 11
2024-03-21T16:08:43-04:00 [INFO] starting language server. binary path: "/Users/oni/Library/Application Support/Zed/languages/clangd/clangd_17.0.3/bin/clangd", working directory: "/Users/oni/Downloads/p4-editor/", args: []
2024-03-21T16:09:18-04:00 [ERROR] crates/lsp/src/lsp.rs:720: oneshot canceled
```

**Comment by JosephTLyons** [comment]
Cool to hear that you got it resolved @OSokunbi - I'll leave this open and see what the team thinks we should do here.

**Comment by AlexL882** [comment]
> managed to fix the issue by running :
> 
> ```
> rm ~/.cache
> mkdir -p ~/.cache
> mkdir -p ~/.cache/zed
> chmod 700 ~/.cache/zed
> ```
> 
> turns out I had a file named .cache in my root directory which was interfering with zed creating a tmp path. checked what the file contents and deleted it as it held unimportant info then created a .cache and in my home directory and then created .cache/zed, then gave my user permissions to the file

Having similar issues after 0.126.3. No files named .cache found, but I tried to remove the existing .cache directory and created a new one as described in the author's comment. Finally able to open Zed with this approach

**Comment by mrnugget** [comment]
> Cool to hear that you got it resolved @OSokunbi - I'll leave this open and see what the team thinks we should do here.

I think ideally we'd check whether we can write to this directory and if not, print an exact error and exit. Or, even better, fall back to a normal temp dir?
